var fs = require('fs');
var src = fs.readFileSync(__dirname + '/interview-data.js', 'utf8');

function esc(s) { return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n'); }

function makeConcept(term, difficulty, definition, extra) {
  var ex = extra || {};
  var parts = ["        { term: '" + esc(term) + "', difficulty: '" + difficulty + "',"];
  parts.push("            definition: '" + esc(definition) + "',");
  if (ex.codeExample) parts.push("            codeExample: '" + esc(ex.codeExample) + "',");
  if (ex.compareWith) parts.push("            compareWith: '" + esc(ex.compareWith) + "',");
  if (ex.keyPoints) parts.push("            keyPoints: " + JSON.stringify(ex.keyPoints) + (ex.commonMistakes||ex.followUps ? ',' : ''));
  if (ex.commonMistakes) parts.push("            commonMistakes: " + JSON.stringify(ex.commonMistakes) + (ex.followUps ? ',' : ''));
  if (ex.followUps) parts.push("            followUps: " + JSON.stringify(ex.followUps));
  parts.push("        }");
  return parts.join('\n');
}

var extras = {
  'react': [
    ['Render Props', 'Intermediate', 'Function prop that controls rendering', {codeExample: '<MouseTracker render={({x,y}) => <h1>{x},{y}</h1>} />', keyPoints: ['Function prop controls render', 'Alternative to HOCs', 'Less common since Hooks']}],
    ['Higher-Order Components', 'Intermediate', 'Function returning a wrapped component', {codeExample: 'function withAuth(Wrapped) {\n    return function(props) {\n        if (!user) return <Login />;\n        return <Wrapped {...props} />;\n    };\n}', keyPoints: ['Takes component, returns component', 'Adds cross-cutting concerns', 'Can cause naming collisions']}],
    ['useReducer', 'Intermediate', 'State management with reducer pattern', {codeExample: 'const [state, dispatch] = useReducer(reducer, initialState);\n// dispatch({type: \'INCREMENT\'})', keyPoints: ['Reducer: (state, action) => newState', 'Good for complex state logic', 'Alternative to useState']}],
    ['useCallback & useMemo', 'Intermediate', 'Memoization hooks for performance', {codeExample: 'const memoized = useCallback(() => { doSomething(a, b); }, [a, b]);\nconst computed = useMemo(() => expensive(a, b), [a, b]);', keyPoints: ['useCallback: memoizes function ref', 'useMemo: memoizes computed value', 'Deps array controls recalculation']}],
    ['Custom Hooks', 'Intermediate', 'Reusable stateful logic', {codeExample: 'function useWindowSize() {\n    const [size, setSize] = useState({w: window.innerWidth, h: window.innerHeight});\n    useEffect(() => { const h = () => setSize({w: window.innerWidth, h: window.innerHeight}); window.addEventListener(\'resize\', h); return () => window.removeEventListener(\'resize\', h); }, []);\n    return size;\n}', keyPoints: ['Functions starting with "use"', 'Can call other hooks', 'Share logic, not state']}],
  ],
  'sql': [
    ['Subqueries', 'Intermediate', 'Nested queries within SELECT, FROM, or WHERE', {codeExample: 'SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);', keyPoints: ['Correlated vs non-correlated', 'Can appear in SELECT, FROM, WHERE', 'EXISTS and NOT EXISTS']}],
    ['JOINs (Inner, Outer, Cross)', 'Intermediate', 'Combining rows from multiple tables', {codeExample: 'SELECT * FROM orders o\nINNER JOIN customers c ON o.customer_id = c.id\nLEFT JOIN addresses a ON c.id = a.customer_id\nFULL OUTER JOIN payments p ON o.id = p.order_id;', keyPoints: ['INNER: matching rows only', 'LEFT/RIGHT: preserve one side', 'CROSS: Cartesian product']}],
    ['Union & Intersect', 'Intermediate', 'Set operations on query results', {codeExample: 'SELECT name FROM employees\nUNION\nSELECT name FROM contractors;\n-- UNION ALL includes duplicates', keyPoints: ['UNION: distinct rows', 'UNION ALL: includes duplicates', 'Columns must match']}],
    ['Constraints (PK, FK, Unique, Check)', 'Beginner', 'Rules enforced at database level', {codeExample: 'CREATE TABLE orders (\n    id INT PRIMARY KEY,\n    user_id INT REFERENCES users(id),\n    email VARCHAR(255) UNIQUE,\n    amount DECIMAL CHECK (amount > 0)\n);', keyPoints: ['PK: unique + not null', 'FK: referential integrity', 'Check: custom validation']}],
    ['GROUP BY & HAVING', 'Intermediate', 'Aggregating data with grouping', {codeExample: 'SELECT department, AVG(salary), COUNT(*)\nFROM employees\nGROUP BY department\nHAVING AVG(salary) > 50000;', keyPoints: ['GROUP BY before HAVING', 'HAVING filters groups (after agg)', 'WHERE filters rows (before agg)']}],
  ],
  'html': [
    ['Accessibility (ARIA)', 'Beginner', 'Making web content accessible', {codeExample: '<button aria-label="Close" onclick="close()">X</button>\n<div role="alert">Error occurred</div>\n<nav aria-label="Main navigation">...</nav>', keyPoints: ['ARIA roles, states, properties', 'Semantic HTML first', 'aria-label for screen readers']}],
    ['Forms & Validation', 'Intermediate', 'HTML form elements and built-in validation', {codeExample: '<form>\n    <input type="email" required minlength="3" pattern="[a-z]+">\n    <datalist id="browsers"><option value="Chrome"></datalist>\n    <output name="result"></output>\n</form>', keyPoints: ['Input types: email, tel, number, date', 'Constraint validation API', 'Datalist for autocomplete']}],
    ['SVG', 'Intermediate', 'Scalable vector graphics inline', {codeExample: '<svg width="100" height="100">\n    <circle cx="50" cy="50" r="40" fill="red" stroke="black"/>\n    <rect x="10" y="10" width="30" height="30" fill="blue"/>\n</svg>', keyPoints: ['XML-based vector format', 'Scalable without quality loss', 'Manipulable with CSS/JS']}],
  ],
  'css': [
    ['Pseudo-classes & Pseudo-elements', 'Intermediate', 'Styling based on state or content parts', {codeExample: '.btn:hover { background: blue; }\n.btn:focus-visible { outline: 2px solid; }\nli:first-child { font-weight: bold; }\ninput:checked + label { color: green; }\np::first-line { font-variant: small-caps; }\n.my-el::before { content: "> "; }', keyPoints: [':hover, :focus, :active, :checked', '::before, ::after (content)', ':nth-child(), :first-child']}],
    ['CSS Specificity & Cascade', 'Beginner', 'How browsers resolve conflicting CSS rules', {codeExample: '/* Specificity: inline > id > class > element */\n#header .nav a  /* 0,1,1,1 */\n.nav a         /* 0,0,1,1 */\na              /* 0,0,0,1 */\n/* !important overrides all (avoid) */', keyPoints: ['Inline > ID > Class > Element', '!important breaks cascade', 'Specificity calculator']}],
    ['Positioning (relative, absolute, fixed, sticky)', 'Beginner', 'CSS position property values', {codeExample: '.relative { position: relative; top: 10px; }\n.absolute { position: absolute; top: 0; left: 0; }\n.fixed { position: fixed; bottom: 0; }\n.sticky { position: sticky; top: 0; }', keyPoints: ['Static: default', 'Relative: offset from normal', 'Absolute: relative to positioned ancestor', 'Sticky: hybrid relative/fixed']}],
  ],
  'git': [
    ['Stashing', 'Beginner', 'Temporarily saving uncommitted changes', {codeExample: 'git stash push -m "WIP feature"\ngit stash list\ngit stash pop\ngit stash apply stash@{0}\ngit stash drop stash@{0}', keyPoints: ['Stash saves working dir changes', 'pop applies and removes, apply keeps', 'Useful for context switching']}],
    ['Reset vs Revert vs Restore', 'Intermediate', 'Undoing changes in Git', {codeExample: 'git reset --soft HEAD~1  # undo commit, keep changes\nmixed HEAD~1  # undo + unstage\nhard HEAD~1  # discard completely\ngit revert HEAD  # new commit undoing changes\ngit restore file.txt  # discard working changes', keyPoints: ['Reset: moves branch pointer', 'Revert: safe for shared branches', 'Restore: working tree changes']}],
    ['Merge Conflicts', 'Intermediate', 'Resolving conflicting changes from merges', {codeExample: '# Conflict markers:\n<<<<<<< HEAD\nour changes\n=======\ntheir changes\n>>>>>>> branch\n# Resolve manually, then:\ngit add resolved-file\ngit merge --continue', keyPoints: ['Conflicts on same lines', 'Resolve manually or with tool', 'Abort with merge --abort']}],
  ],
  'docker': [
    ['Dockerfile Best Practices', 'Intermediate', 'Optimizing Dockerfiles for size, speed, security', {codeExample: 'FROM node:20-alpine AS base\nRUN apk add --no-cache tini\nUSER node\nWORKDIR /app\nCOPY --chown=node package*.json ./\nRUN npm ci --only=production\nCOPY --chown=node . .\nEXPOSE 3000\nENTRYPOINT ["/sbin/tini", "--"]\nCMD ["node", "server.js"]', keyPoints: ['Use specific tags (avoid latest)', 'Multi-stage to reduce size', '.dockerignore to exclude files', 'Minimal base images (alpine)']}],
    ['Docker Security', 'Intermediate', 'Container security best practices', {codeExample: '# Run as non-root\nRUN addgroup -S app && adduser -S app -G app\nUSER app\n\n# Read-only root filesystem\n$ docker run --read-only --tmpfs /tmp myapp\n\n# Drop capabilities\n$ docker run --cap-drop=ALL --cap-add=NET_BIND_SERVICE myapp\n\n# Security scanning\n$ docker scan myimage', keyPoints: ['Avoid root: create user', 'Drop unnecessary capabilities', 'Read-only root filesystem', 'Scan images for vulnerabilities']}],
    ['Dockerfile Instructions (COPY vs ADD, CMD vs ENTRYPOINT)', 'Intermediate', 'Dockerfile instruction semantics', {codeExample: '# CMD: default arguments\nCMD ["node", "app.js"]\n# ENTRYPOINT: main command\nENTRYPOINT ["docker-entrypoint.sh"]\n# Together: ENTRYPOINT + CMD (default args to entrypoint)\n\n# COPY: local files only\nCOPY . /app\n# ADD: local files + URLs + tar auto-extract\nADD app.tar.gz /app\n\n# ARG vs ENV\nARG BUILD_VAR  # build only\nENV APP_VAR=value  # available at runtime', keyPoints: ['CMD provides defaults, overridable', 'ENTRYPOINT is main command', 'COPY over ADD for local files', 'ARG build-time, ENV run-time']}],
  ],
  'dsa': [
    ['BFS & DFS', 'Intermediate', 'Graph traversal algorithms', {codeExample: 'function bfs(graph, start) {\n    const visited = new Set([start]), queue = [start];\n    while (queue.length) {\n        const v = queue.shift();\n        for (const n of graph[v])\n            if (!visited.has(n)) { visited.add(n); queue.push(n); }\n    }\n}', keyPoints: ['BFS: queue, shortest path', 'DFS: stack/recursion, tree traversal', 'Time: O(V+E)']}],
    ['Dijkstra & A*', 'Advanced', 'Shortest path algorithms', {codeExample: 'function dijkstra(graph, start) {\n    const dist = {}, pq = [[0, start]];\n    dist[start] = 0;\n    while (pq.length) {\n        const [d, v] = pq.sort((a,b)=>a[0]-b[0]).shift();\n        if (d > dist[v]) continue;\n        for (const [n, w] of graph[v])\n            if (dist[n] === undefined || d + w < dist[n])\n                { dist[n] = d + w; pq.push([dist[n], n]); }\n    }\n    return dist;\n}', keyPoints: ['Dijkstra: weighted, no negative', 'A*: heuristic-guided Dijkstra', 'Priority queue for efficiency']}],
    ['Dynamic Programming', 'Advanced', 'Solving by combining subproblem solutions', {codeExample: 'function fib(n, memo={}) {\n    if (n in memo) return memo[n];\n    if (n <= 1) return n;\n    return memo[n] = fib(n-1, memo) + fib(n-2, memo);\n}\n// BOTTOM-UP\nfunction fibBu(n) {\n    let [a, b] = [0, 1];\n    for (let i = 2; i <= n; i++) [a, b] = [b, a + b];\n    return b;\n}', keyPoints: ['Overlapping subproblems', 'Optimal substructure', 'Top-down (memo) vs bottom-up (tab)']}],
  ],
  'cpp': [
    ['STL Containers', 'Intermediate', 'Standard Template Library containers', {codeExample: 'vector<int> v = {1,2,3};\nmap<string, int> m;\nunordered_map<string,int> hm;\nset<int> s;\ndeque<int> dq;\npriority_queue<int> pq;', keyPoints: ['Sequence: vector, deque, list', 'Associative: map, set, multimap', 'Unordered: hash-based O(1) avg']}],
    ['STL Algorithms', 'Intermediate', 'Standard algorithms on containers', {codeExample: 'sort(v.begin(), v.end());\nauto it = find(v.begin(), v.end(), 42);\nint sum = accumulate(v.begin(), v.end(), 0);\ncopy(src.begin(), src.end(), back_inserter(dst));', keyPoints: ['Sort, find, accumulate, copy', 'Predicate-based: find_if, count_if', 'O(n) for most, O(n log n) sort']}],
    ['Const Correctness', 'Intermediate', 'Using const for immutability guarantees', {codeExample: 'const int MAX = 100;\nvoid print(const string& s) { cout << s; }\nclass A {\n    int get() const { return x; }  // const method\n    void set(int v) { x = v; }\n};', keyPoints: ['const variables cannot change', 'const& params avoid copy + promise', 'const methods on const objects']}],
  ],
  'typescript': [
    ['Enums', 'Beginner', 'Named constants with numeric or string values', {codeExample: 'enum Direction { Up, Down, Left, Right }\nenum Status { Active = "ACTIVE", Inactive = "INACTIVE" }', keyPoints: ['Auto-incrementing numeric', 'String enums for readability', 'Const enums are inlined']}],
    ['Namespace vs Modules', 'Intermediate', 'Organizing code into logical groups', {codeExample: 'namespace Validation {\n    export interface Validator { validate(s: string): boolean; }\n}\n// Prefer ES modules:\n// types.ts\nexport interface Validator { validate(s: string): boolean; }', keyPoints: ['Namespaces: internal modules', 'ES modules: external', 'Modules are preferred']}],
    ['Declaration Files (.d.ts)', 'Intermediate', 'Type declarations for JS libraries', {codeExample: '// lodash.d.ts\ndeclare module "lodash" {\n    export function chunk<T>(arr: T[], size: number): T[][];\n}\ndeclare var process: { env: { [k: string]: string | undefined }; };', keyPoints: ['declare module for library types', 'declare var for globals', '@types/ packages for popular libs']}],
  ],
  'go': [
    ['Structs & Methods', 'Beginner', 'Composite types with attached methods', {codeExample: 'type Rect struct { W, H float64 }\nfunc (r Rect) Area() float64 { return r.W * r.H }\nfunc (r *Rect) Scale(f float64) { r.W *= f; r.H *= f }', keyPoints: ['Value receiver vs pointer receiver', 'No classes, methods on types', 'Embedding for composition']}],
    ['Packages & Modules', 'Intermediate', 'Go module system for dependency management', {codeExample: 'go mod init example.com/myapp\ngo get github.com/gin-gonic/gin\ngo mod tidy\ngo mod vendor', keyPoints: ['go.mod tracks dependencies', 'Module path + semantic version', 'Vendor directory for offline builds']}],
    ['Testing (Table-driven)', 'Intermediate', 'Go testing conventions and patterns', {codeExample: 'func TestAdd(t *testing.T) {\n    tests := []struct{a,b,want int}{\n        {1,2,3},\n        {0,0,0},\n        {-1,1,0},\n    }\n    for _, tt := range tests {\n        if got := add(tt.a, tt.b); got != tt.want { t.Errorf("add(%d,%d)=%d", tt.a, tt.b, got) }\n    }\n}', keyPoints: ['Test files: *_test.go', 'Table-driven tests idiomatic', 'go test -v for verbose']}],
  ],
  'rust': [
    ['Structs & Impl', 'Beginner', 'Define types and implement methods', {codeExample: 'struct Rect { w: f64, h: f64 }\nimpl Rect {\n    fn area(&self) -> f64 { self.w * self.h }\n    fn scale(&mut self, f: f64) { self.w *= f; self.h *= f; }\n}', keyPoints: ['impl block for methods', '&self for read, &mut self for write', 'Associated functions without self']}],
    ['Enums & Match', 'Beginner', 'Algebraic data types with pattern matching', {codeExample: 'enum Option<T> { Some(T), None }\nlet x: Option<i32> = Some(42);\nmatch x {\n    Some(v) => println!("Got {}", v),\n    None => println!("Nothing"),\n}', keyPoints: ['match is exhaustive', 'Option and Result built-in enums', 'if let for single-arm matching']}],
    ['Cargo & Crates', 'Beginner', 'Rust package manager and build tool', {codeExample: 'cargo new myapp\ncargo add serde --features derive\ncargo build --release\ncargo test\ncargo doc --open\ncargo clippy\ncargo fmt', keyPoints: ['Cargo.toml for dependencies', 'cargo build/test/run', 'Clippy for linting, rustfmt for formatting']}],
  ],
  'mysql': [
    ['Normalization Forms', 'Intermediate', 'Database normalization principles', {codeExample: '-- 1NF: atomic columns, no repeating groups\n-- 2NF: 1NF + no partial dependency\n-- 3NF: 2NF + no transitive dependency\n-- Example: separate addresses table', keyPoints: ['1NF: atomic values', '2NF: full key dependency', '3NF: no transitive dependency']}],
    ['Transactions', 'Intermediate', 'ACID transaction control', {codeExample: 'START TRANSACTION;\nSAVEPOINT sp1;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;\n-- ROLLBACK TO sp1; -- partial rollback', keyPoints: ['START TRANSACTION / COMMIT / ROLLBACK', 'SAVEPOINT for partial rollback', 'AUTOCOMMIT setting']}],
    ['Views', 'Intermediate', 'Virtual tables from queries', {codeExample: 'CREATE VIEW active_users AS\nSELECT * FROM users WHERE deleted_at IS NULL;\n\n-- Updatable views (simple)\nINSERT INTO active_users (name, email) VALUES (\'John\', \'john@test.com\');', keyPoints: ['Simplifies complex queries', 'Provides security layer', 'Updatable under certain conditions']}],
  ],
  'linux': [
    ['Text Processing (grep, sed, awk)', 'Intermediate', 'Command-line text manipulation tools', {codeExample: 'grep -r "ERROR" /var/log/\nsed -i \'s/old/new/g\' file.txt\nawk \'{print $1, $3}\' data.csv\nsort file | uniq -c\nwc -l file.txt', keyPoints: ['grep: search patterns', 'sed: stream editor (find/replace)', 'awk: field-based processing']}],
    ['File Descriptors & Redirection', 'Intermediate', 'Standard streams and I/O redirection', {codeExample: 'cmd > out.txt 2>&1    # stdout + stderr to file\ncmd >> log.txt         # append\ncmd < input.txt        # stdin from file\ncmd1 | cmd2            # pipe stdout to stdin of cmd2\nexec 3<file.txt        # custom fd\nls /proc/$$/fd/        # list open FDs', keyPoints: ['stdin(0), stdout(1), stderr(2)', '> overwrite, >> append, < input', '| pipe between commands']}],
    ['Cron & Scheduling', 'Intermediate', 'Automating tasks with cron', {codeExample: '# crontab -e\n# m h dom mon dow command\n0 3 * * * /usr/bin/backup.sh              # daily 3am\n*/15 * * * * /usr/bin/healthcheck.sh     # every 15 min\n0 0 1 * * /usr/bin/monthly_report.sh    # 1st of month\n@reboot /usr/bin/start_service.sh        # on boot', keyPoints: ['crontab -e to edit', 'Five fields: min hour dom mon dow', '@reboot, @daily, @hourly shorthands']}],
  ],
  'mongodb': [
    ['CRUD Operations', 'Beginner', 'Create, read, update, delete documents', {codeExample: 'db.users.insertOne({name:"John", age:30})\ndb.users.find({age: {$gt: 25}}).sort({name:1}).limit(10)\ndb.users.updateOne({name:"John"}, {$set: {age:31}})\ndb.users.deleteOne({name:"John"})', keyPoints: ['insertOne/insertMany', 'find with query operators', 'updateOne/updateMany with $set', 'deleteOne/deleteMany']}],
    ['Schema Design', 'Intermediate', 'Embedding vs referencing in document DB', {codeExample: '// Embed (one-to-few):\n{\n    _id: "user1",\n    name: "John",\n    addresses: [{street:"123 Main", city:"NYC"}]\n}\n// Reference (one-to-many):\n{\n    _id: "order1",\n    user_id: "user1",\n    items: ["item1", "item2"]  // references\n}', keyPoints: ['Embed for one-to-few', 'Reference for many-to-many', 'Avoid unbounded arrays']}],
    ['Transactions', 'Advanced', 'Multi-document ACID transactions', {codeExample: 'const session = db.getMongo().startSession();\nsession.startTransaction();\ntry {\n    session.getDatabase("db").orders.insertOne({...});\n    session.getDatabase("db").inventory.updateOne({...});\n    session.commitTransaction();\n} catch (e) {\n    session.abortTransaction();\n} finally { session.endSession(); }', keyPoints: ['Multi-document transactions (4.0+)', 'Cross-collection and cross-db', 'Higher latency than single doc ops']}],
  ],
  'c': [
    ['Strings (char arrays)', 'Beginner', 'C-style null-terminated strings', {codeExample: 'char s[] = "hello";\nchar *p = s;\nprintf("%s", s);\nprintf("%c", s[0]);\nstrlen(s); strcpy(dst, src); strcmp(a,b); strcat(dst, src);', keyPoints: ['Null-terminated (\\0)', 'No bounds checking', 'strcpy/strcat/strcmp/strlen']}],
    ['Dynamic Arrays (realloc)', 'Intermediate', 'Resizing arrays dynamically', {codeExample: 'int *arr = malloc(4 * sizeof(int));\narr = realloc(arr, 8 * sizeof(int));\nif (arr == NULL) { /* handle */ }\narr[7] = 42;\nfree(arr);', keyPoints: ['realloc resizes or moves', 'May return different pointer', 'Check return for NULL', 'Original pointer freed if realloc fails']}],
    ['Bit Manipulation', 'Intermediate', 'Bitwise operators for low-level operations', {codeExample: 'unsigned int x = 0b1010;\nx & 0b1111  // AND\nx | 0b0101  // OR\nx ^ 0b1111  // XOR\nx << 2      // left shift\nx >> 1      // right shift\n// Check bit n: (x >> n) & 1\n// Set bit n:  x |= (1 << n)\n// Clear bit n: x &= ~(1 << n)', keyPoints: ['&, |, ^, ~, <<, >> operators', 'Used in flags, compression, crypto', 'Endianness matters for multi-byte']}],
  ],
  'csharp': [
    ['Properties & Indexers', 'Beginner', 'Member access with get/set logic', {codeExample: 'class Person {\n    public string Name { get; set; }  // auto-property\n    private int _age;\n    public int Age {\n        get => _age;\n        set => _age = value >= 0 ? value : throw new ArgumentException();\n    }\n    public string this[int idx] => _items[idx];  // indexer\n}', keyPoints: ['Auto-properties for simple fields', 'Expression-bodied members', 'Indexers for collection-like access']}],
    ['Generics', 'Intermediate', 'Type-parameterized classes and methods', {codeExample: 'class Repository<T> where T : IEntity {\n    private List<T> _items = new();\n    public void Add(T item) => _items.Add(item);\n    public T? Get(int id) => _items.FirstOrDefault(e => e.Id == id);\n}', keyPoints: ['where T : constraint', 'Type safety without boxing', 'Generic methods, classes, interfaces']}],
    ['Extension Methods', 'Intermediate', 'Adding methods to existing types', {codeExample: 'public static class StringExtensions {\n    public static bool IsEmail(this string s) =>\n        s.Contains("@") && s.Contains(".");\n}\n"test@test.com".IsEmail();  // true', keyPoints: ['static class + static method with this', 'Cannot access private members', 'Used by LINQ (IEnumerable extensions)']}],
  ],
  'kotlin': [
    ['Collections & Lambdas', 'Beginner', 'Functional operations on collections', {codeExample: 'list.filter { it > 5 }.map { it * 2 }.sorted().take(3)\nval sum = numbers.reduce { a, b -> a + b }\nval grouped = people.groupBy { it.age / 10 * 10 }', keyPoints: ['filter, map, flatMap, reduce', 'Sequence for lazy evaluation', 'Mutable vs immutable (List vs MutableList)']}],
    ['Object Declarations & Companion Objects', 'Intermediate', 'Singleton pattern and static-like members', {codeExample: 'object Singleton {\n    fun getInstance(): Singleton = this\n}\nclass MyClass {\n    companion object {\n        const val TAG = "MyClass"\n        fun create() = MyClass()\n    }\n}', keyPoints: ['object: singleton declaration', 'companion object: static members', 'Can implement interfaces']}],
    ['Delegated Properties', 'Intermediate', 'Property delegation with by keyword', {codeExample: 'class ViewModel {\n    val data by lazy { loadExpensiveData() }\n    var name by Delegates.observable("") { _, old, new -> println("$old -> $new") }\n    val prefs by Delegates.notNull<String>()\n}', keyPoints: ['lazy: computed on first access', 'observable/vetoable listeners', 'Custom delegates']}],
  ],
  'swift': [
    ['Value vs Reference Types', 'Beginner', 'Struct (value) vs Class (reference)', {codeExample: 'struct Point { var x, y: Double }  // value\nclass Person { var name: String }  // reference\n\nvar p1 = Point(x: 1, y: 2)\nvar p2 = p1  // copy (independent)\np2.x = 5  // p1.x is still 1\n\nvar c1 = Person()\nvar c2 = c1  // reference (same instance)', keyPoints: ['Struct: value, copied, immutable by default', 'Class: reference, heap allocated', 'Prefer structs for data types']}],
    ['Optionals', 'Beginner', 'Safe handling of absent values', {codeExample: 'var name: String? = nil\nif let name = name { print("Hello, \\(name)") }\nlet length = name?.count ?? 0\nlet sure = name!  // crash if nil\nfunc process(_ s: String?) { guard let s = s else { return } }', keyPoints: ['? for optional type', 'if let and guard let for binding', '?? nil-coalescing operator', 'Optional chaining with ?.']}],
    ['Property Observers', 'Intermediate', 'Monitoring property changes', {codeExample: 'class StepCounter {\n    var steps = 0 {\n        willSet { print("About to set \\(newValue)") }\n        didSet { print("Was \\(oldValue), now \\(steps)") }\n    }\n}', keyPoints: ['willSet: before change (newValue)', 'didSet: after change (oldValue)', 'Not called during init']}],
  ],
  'pandas': [
    ['Reading/Writing Data', 'Beginner', 'Importing and exporting various formats', {codeExample: 'df = pd.read_csv("data.csv")\ndf = pd.read_excel("data.xlsx", sheet_name="Sheet1")\ndf = pd.read_json("data.json")\ndf.to_csv("output.csv", index=False)\ndf.to_parquet("output.parquet")', keyPoints: ['read_csv/excel/json/parquet/sql', 'to_csv/excel/json for export', 'Parameter: index, columns, dtype']}],
    ['Pivot Tables & Crosstab', 'Intermediate', 'Summarizing data in matrix format', {codeExample: 'pd.pivot_table(df, values=\'sales\', index=\'region\', columns=\'product\', aggfunc=\'sum\', margins=True)\npd.crosstab(df[\'dept\'], df[\'gender\'], normalize=\'index\')', keyPoints: ['pivot_table: multi-level summary', 'crosstab: frequency table', 'margins for row/column totals']}],
    ['Data Cleaning', 'Intermediate', 'Common data cleaning operations', {codeExample: 'df.drop_duplicates()\ndf[\'col\'] = df[\'col\'].str.strip().str.lower()\ndf[\'date\'] = pd.to_datetime(df[\'date\'])\ndf = df.rename(columns={"old": "new"})\ndf = df.replace({np.nan: 0, "N/A": None})\ndf[\'col\'] = df[\'col\'].astype(\'float32\')', keyPoints: ['drop_duplicates, rename, replace', 'String accessor .str.*', 'astype for type conversion']}],
  ],
  'security': [
    ['Cryptography Basics', 'Intermediate', 'Hashing, symmetric, asymmetric encryption', {codeExample: '// Hashing (SHA-256)\nconst crypto = require(\'crypto\');\ncrypto.createHash(\'sha256\').update(\'data\').digest(\'hex\');\n// Symmetric (AES)\ncrypto.createCipheriv(\'aes-256-gcm\', key, iv);\n// Asymmetric (RSA)\ncrypto.generateKeyPairSync(\'rsa\', {modulusLength: 4096});', keyPoints: ['Hashing: one-way, SHA-256', 'Symmetric: same key (AES)', 'Asymmetric: public/private (RSA)']}],
    ['CSRF Protection', 'Intermediate', 'Cross-Site Request Forgery prevention', {codeExample: '// Anti-CSRF token\n<form>\n    <input type="hidden" name="_csrf" value="{{csrfToken}}">\n</form>\n// SameSite cookie attribute\nSet-Cookie: session=abc; SameSite=Strict\n// Custom header check\n// Double-submit cookie pattern', keyPoints: ['CSRF token per session', 'SameSite cookie attribute', 'Custom request header validation']}],
    ['Authentication Methods (MFA, SSO)', 'Intermediate', 'Multi-factor and single sign-on', {codeExample: '// MFA: TOTP\nconst speakeasy = require(\'speakeasy\');\nconst secret = speakeasy.generateSecret();\nconst token = speakeasy.totp({secret: secret.base32, encoding: \'base32\'});\nconst valid = speakeasy.totp.verify({secret: secret.base32, token, encoding: \'base32\', window: 1});', keyPoints: ['MFA: something you know + have/are', 'TOTP: time-based one-time password', 'SSO: SAML, OIDC']}],
  ],
  'dbms': [
    ['Transactions & Concurrency', 'Intermediate', 'Managing concurrent database access', {codeExample: '-- Lost update: two tx read same row, write different values\n-- Dirty read: read uncommitted data\n-- Non-repeatable read: same query, different results\n-- Phantom read: new rows appear in second query\n\n-- Serializable: highest isolation, lowest concurrency', keyPoints: ['Lost update, dirty read, non-repeatable, phantom', 'Isolation levels solve different anomalies', 'Locking vs MVCC approach']}],
    ['ER Diagrams', 'Beginner', 'Entity-Relationship modeling', {codeExample: '[Customer] 1---* [Order] *---1 [Product]\n// Relationships:\n// 1:1, 1:N, M:N\n// Attributes: simple, composite, derived, multi-valued\n// Weak entity: depends on strong entity', keyPoints: ['Entities, relationships, attributes', 'Cardinality: 1:1, 1:N, M:N', 'Primary key, foreign key']}],
    ['Index Types (B-Tree, Hash, Bitmap)', 'Intermediate', 'Different index structures and use cases', {codeExample: '-- B-Tree: default, good for range/equality, sorts\nCREATE INDEX idx_name ON users(name);\n-- Hash: exact match only, faster for = \nCREATE INDEX idx_hash ON users USING HASH(id);\n-- Bitmap: low cardinality columns (gender, status)\n-- GiST: geometric, full-text (PostgreSQL)\n-- GIN: inverted index (arrays, JSONB)', keyPoints: ['B-Tree: balanced tree, range queries', 'Hash: exact match only', 'Bitmap: low cardinality, column stores']}],
  ],
  'oop': [
    ['Polymorphism (Compile-time & Runtime)', 'Intermediate', 'Method overloading vs overriding', {codeExample: '// Compile-time (overloading)\nclass Calc {\n    int add(int a, int b) { return a + b; }\n    double add(double a, double b) { return a + b; }\n}\n// Runtime (overriding)\nclass Animal { void speak() { print("generic"); } }\nclass Dog extends Animal { void speak() { print("bark"); } }', keyPoints: ['Overloading: same name, different params (compile-time)', 'Overriding: subclass redefinition (runtime)', 'Virtual dispatch for runtime poly']}],
    ['Abstraction & Encapsulation', 'Beginner', 'Hiding complexity and protecting data', {codeExample: 'class BankAccount {\n    #balance = 0;  // private\n    deposit(amount) {\n        if (amount <= 0) throw new Error("Invalid");\n        this.#balance += amount;\n    }\n    getBalance() { return this.#balance; }\n}', keyPoints: ['Abstraction: hide implementation', 'Encapsulation: data hiding (private)', 'Public API + private internals']}],
    ['Interface vs Abstract Class', 'Intermediate', 'Contract vs partial implementation', {codeExample: '// Interface: pure contract\ninterface Drawable { void draw(); }\n// Abstract: partial implementation\nabstract class Shape {\n    abstract double area();\n    void print() { System.out.println("Area: " + area()); }\n}', keyPoints: ['Interface: all abstract, multiple inheritance', 'Abstract: can have implementation', 'Java 8+ interfaces with default methods']}],
  ],
  'os': [
    ['Interrupts & System Calls', 'Intermediate', 'Hardware interrupts and kernel entry points', {codeExample: '// System call flow:\n// 1. User code calls open() in libc\n// 2. libc executes syscall instruction\n// 3. CPU switches to kernel mode\n// 4. Kernel handles syscall\n// 5. Returns to user mode\n// In Linux: int 0x80 (old) or syscall (modern)', keyPoints: ['Interrupts: hardware signals', 'System calls: user -> kernel transition', 'Context switch saves/restores state']}],
    ['Virtualization & Hypervisors', 'Advanced', 'Virtual machine monitors and types', {codeExample: '// Type 1 (bare-metal): VMware ESXi, Xen, Hyper-V\n// Runs directly on hardware\n// Type 2 (hosted): VirtualBox, VMware Workstation\n// Runs on host OS\n// Container: Docker (OS-level, shares kernel)\n// Benefits: isolation, utilization, migration', keyPoints: ['Type 1: hypervisor on bare metal', 'Type 2: hypervisor on host OS', 'Containers: OS-level virtualization']}],
    ['Race Conditions & Critical Sections', 'Intermediate', 'Concurrency problems and solutions', {codeExample: '// Race condition: two threads increment counter\n// Thread A: read count (5), add 1 (6)\n// Thread B: read count (5), add 1 (6)\n// Result: 6 instead of 7!\n\n// Solution: atomic operation or mutex\natomic<int> counter;\ncounter.fetch_add(1);  // atomic RMW', keyPoints: ['Race: timing-dependent wrong results', 'Critical section: mutex-protected code', 'Atomic operations: hardware-level']}],
  ],
  'networks': [
    ['DHCP', 'Intermediate', 'Dynamic Host Configuration Protocol', {codeExample: '// DORA:\n// Discover: client broadcasts "any DHCP server?"\n// Offer: server offers IP\n// Request: client requests offered IP\n// Ack: server confirms\n// Lease time: how long IP is valid\n// Renewal: client renews before expiry', keyPoints: ['DORA: Discover, Offer, Request, Ack', 'Lease management with renewal', 'Automatic IP configuration']}],
    ['NAT Types (Static, Dynamic, PAT)', 'Intermediate', 'Network Address Translation types', {codeExample: '// Static NAT: 1:1 mapping (public IP <-> private IP)\n// Dynamic NAT: pool of public IPs\n// PAT (Port Address Translation): many:1 with port\n// Home router: 192.168.1.x -> single public IP with PAT\n// ip nat inside source list 1 interface Gig0/0 overload', keyPoints: ['Static: one-to-one', 'Dynamic: pool-based', 'PAT: many-to-one with port multiplexing']}],
    ['VLANs & Subnetting', 'Intermediate', 'Network segmentation at Layer 2', {codeExample: '// VLAN: virtual LAN, 802.1Q tag\n// Trunk: carries multiple VLANs between switches\n// Access port: single VLAN for end device\n// Benefits: broadcast domain isolation, security\n// VLAN 1: Management (native)\n// VLAN 10: Users - 192.168.10.0/24\n// VLAN 20: Servers - 192.168.20.0/24', keyPoints: ['VLAN: L2 segmentation', 'Trunk ports carry multiple VLANs', 'Reduces broadcast domain size']}],
  ],
  'system-design': [
    ['Consistent Hashing', 'Intermediate', 'Distributed hashing minimizing rehashing on node changes', {codeExample: '// Hash ring: 0 to 2^32-1\n// Nodes placed on ring by hash(node_id)\n// Keys assigned to next clockwise node\n// Virtual nodes for balance\n// Adding/removing node only affects neighbors\nfunction consistentHash(key, nodes) {\n    const hash = hashCode(key);\n    // find next node clockwise\n    for (const node of sortedNodes) {\n        if (hash <= node.hash) return node;\n    }\n    return sortedNodes[0];  // wrap around\n}', keyPoints: ['Minimal reshuffling on node changes', 'Virtual nodes for load balance', 'Used in DynamoDB, Cassandra']}],
    ['Blob Storage (S3) Design', 'Intermediate', 'Object storage system design', {codeExample: '// Components:\n// - Object: key + data + metadata\n// - Bucket: container for objects\n// - Namespace: globally unique bucket name\n// - Storage: distributed file system\n// \n// PUT /bucket/key -> 200 (created)\n// GET /bucket/key -> 200 + data\n// \n// Data placement:\n// - Hash key -> partition\n// - Replicas across availability zones\n// - Eventual consistency for overwrites\n\n// Scaling:\n// - Front-end: load balanced REST servers\n// - Metadata: sharded DB (bucket -> [partitions])\n// - Storage: distributed FS (e.g., HDFS, Ceph)', keyPoints: ['Object = key + data + metadata', 'Flat namespace (buckets)', 'Eventual consistency model', 'Gigabytes to exabytes']}],
    ['Distributed ID Generation', 'Intermediate', 'Unique ID generation at scale', {codeExample: '// Snowflake (Twitter):\n// 64-bit ID:\n// [1-bit unused][41-bit timestamp][10-bit worker][12-bit sequence]\n// - 41 bits: ~69 years of millis\n// - 10 bits: 1024 workers\n// - 12 bits: 4096 IDs per ms per worker\n\n// UUID v4: random, 128-bit\n// - 32 hex chars: 550e8400-e29b-41d4-a716-446655440000\n// - Pros: no coordination needed\n// - Cons: not sortable, larger index\n\n// Database sequences (auto-increment)\n// - Simple but not distributed-friendly\n\n// Instagram approach:\n// - Use logical shard ID in ID\n// - [41-bit timestamp][13-bit shard][10-bit auto-increment]', keyPoints: ['Snowflake: timestamp + worker + sequence', 'UUID: globally unique, not sortable', 'Need: unique, sortable, scalable']}],
  ],
};

var courseIds = Object.keys(extras);
courseIds.sort().reverse();

courseIds.forEach(function(courseId) {
  var concepts = extras[courseId];
  var topicName = courseId.replace(/-/g, ' ').replace(/\b\w/g, function(c) { return c.toUpperCase(); }) + ' Extras';
  var conceptsText = concepts.map(function(c) {
    return makeConcept(c[0], c[1], c[2], c[3]);
  }).join(',\n');

  var courseStart = "  '" + courseId + "': {";
  var pos = src.indexOf(courseStart);
  if (pos < 0) { console.log('NOT FOUND: ' + courseId); return; }

  var closeMarker = "    ]\n  },";
  var closePos = src.indexOf(closeMarker, pos + courseStart.length);
  if (closePos < 0) {
    closeMarker = "    ]\n  }";
    closePos = src.lastIndexOf(closeMarker);
    if (closePos < 0 || closePos < pos) { console.log('NO CLOSE: ' + courseId); return; }
  }

  src = src.slice(0, closePos - 1) + ',\n      { name: \'' + topicName + '\', concepts: [\n' + conceptsText + '\n      ]},' + '\n' + src.slice(closePos);
  console.log('OK: ' + courseId);
});

fs.writeFileSync(__dirname + '/interview-data.js', src, 'utf8');
console.log('DONE');
