// Reads interview-data.js, appends more concepts to each topic, writes back
var fs = require('fs');
var src = fs.readFileSync(__dirname + '/interview-data.js', 'utf8');
// Append more concepts right before each ]); that closes a concepts array
var extraConcepts = {
  python: [
    { term: 'Generators', difficulty: 'Intermediate', definition: 'Functions that yield values lazily using yield keyword', codeExample: 'def fib():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\ngen = fib()\nfor _ in range(5):\n    print(next(gen))', codeOutput: '0\\n1\\n1\\n2\\n3', keyPoints: ['Lazy evaluation saves memory', 'State preserved between yields', 'Can be used in for loops directly', 'Generator expressions use () syntax'] },
    { term: 'Context Managers', difficulty: 'Intermediate', definition: 'Objects that define setup/teardown using with statement', codeExample: 'class FileManager:\n    def __init__(self, filename):\n        self.filename = filename\n    def __enter__(self):\n        self.file = open(self.filename, \'r\')\n        return self.file\n    def __exit__(self, *args):\n        self.file.close()\nwith FileManager(\'test.txt\') as f:\n    print(f.read())', keyPoints: ['__enter__ and __exit__ methods', 'contextlib.contextmanager decorator', 'Exception handling in __exit__', 'Used for resources like files, locks'] },
    { term: 'Lambda Functions', difficulty: 'Beginner', definition: 'Small anonymous functions defined with lambda keyword', codeExample: 'square = lambda x: x ** 2\nprint(square(5))  # 25\npairs = [(1, \'one\'), (3, \'three\'), (2, \'two\')]\nsorted(pairs, key=lambda p: p[0])', keyPoints: ['Single expression only', 'Useful with map, filter, sorted', 'More readable than full def for simple logic'], commonMistakes: ['Using lambda for complex logic', 'Overusing when def is clearer'] },
    { term: 'String Formatting', difficulty: 'Beginner', definition: 'Methods for embedding variables in strings', codeExample: 'name = "Alice"\nage = 30\n# f-strings (Python 3.6+)\nprint(f"{name} is {age} years old")\n# .format()\nprint("{} is {} years old".format(name, age))\n# % formatting\nprint("%s is %d years old" % (name, age))', keyPoints: ['f-strings are fastest and most readable', '.format() for complex formatting', '% formatting for legacy code'], compareWith: 'printf-style formatting in C' },
    { term: 'Iterators', difficulty: 'Beginner', definition: 'Objects that implement __iter__ and __next__ for sequential access', codeExample: 'class CountDown:\n    def __init__(self, n):\n        self.n = n\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.n <= 0:\n            raise StopIteration\n        self.n -= 1\n        return self.n + 1\nfor x in CountDown(3):\n    print(x)  # 3, 2, 1', keyPoints: ['All iterables have __iter__', 'All iterators have __iter__ and __next__', 'for loops call iter() on the iterable', 'StopIteration signals end'] },
    { term: 'Map/Filter/Reduce', difficulty: 'Intermediate', definition: 'Functional programming tools for transforming collections', codeExample: 'nums = [1, 2, 3, 4, 5]\nsquared = list(map(lambda x: x**2, nums))\nevens = list(filter(lambda x: x % 2 == 0, nums))\nfrom functools import reduce\nsum_all = reduce(lambda a, b: a + b, nums)', keyPoints: ['map applies function to every item', 'filter keeps items where function is True', 'reduce cumulatively applies function', 'List comprehensions often replace map/filter'], commonMistakes: ['Forgetting to wrap in list() for eager evaluation'] },
    { term: 'Sets', difficulty: 'Beginner', definition: 'Unordered collection of unique elements with set operations', codeExample: 'a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(a | b)  # union: {1,2,3,4,5,6}\nprint(a & b)  # intersection: {3,4}\nprint(a - b)  # difference: {1,2}\nprint(a ^ b)  # symmetric diff: {1,2,5,6}', keyPoints: ['O(1) average membership test', 'Set literals use {}', 'Frozenset is immutable version', 'Removes duplicates automatically'], commonMistakes: ['Using {} creates empty dict, not set', 'Assuming sets maintain order'] },
    { term: 'Property Decorator', difficulty: 'Intermediate', definition: 'Create managed attributes using @property decorator', codeExample: 'class Circle:\n    def __init__(self, radius):\n        self._radius = radius\n    \n    @property\n    def radius(self):\n        return self._radius\n    \n    @radius.setter\n    def radius(self, value):\n        if value < 0:\n            raise ValueError("Radius cannot be negative")\n        self._radius = value\n    \n    @property\n    def area(self):\n        return 3.14 * self._radius ** 2', keyPoints: ['Getter, setter, deleter via decorators', 'Computed properties like area', 'Encapsulation without explicit getter/setter methods'] },
    { term: 'Deep vs Shallow Copy', difficulty: 'Intermediate', definition: 'Copying objects with different levels of nesting handling', codeExample: 'import copy\noriginal = [[1, 2], [3, 4]]\nshallow = copy.copy(original)\ndeep = copy.deepcopy(original)\nshallow[0][0] = 99  # affects original too!\noriginal[0][0]  # 99 with shallow copy\noriginal[0][0]  # still 1 with deep copy', keyPoints: ['Shallow copy copies references', 'Deep copy creates completely independent copy', 'copy.copy() vs copy.deepcopy()', 'Affects nested mutable objects'], compareWith: 'copy vs deepcopy' },
    { term: 'Python vs Java', difficulty: 'Intermediate', definition: 'Key differences between Python and Java for interviews', keyPoints: ['Python: dynamic typing, interpreted, duck typing', 'Java: static typing, compiled, explicit interfaces', 'Python: indentation-based blocks', 'Java: brace-delimited blocks', 'Python: multiple inheritance via mixins', 'Java: single inheritance with interfaces'], compareWith: 'Java', scenario: 'Your team is choosing between Python and Java for a new microservice. Compare their strengths for this use case.' }
  ],
  javascript: [
    { term: 'IIFE', difficulty: 'Intermediate', definition: 'Immediately Invoked Function Expression', codeExample: '(function() {\n    var privateVar = "secret";\n    console.log("IIFE executed");\n})();\n// privateVar not accessible here\n\n// With arrow function\n(() => {\n    console.log("Arrow IIFE");\n})();', keyPoints: ['Creates private scope', 'Runs immediately after definition', 'Common in module patterns before ES6', 'Avoids polluting global namespace'] },
    { term: 'this Keyword', difficulty: 'Intermediate', definition: 'Context-dependent reference to the current execution scope', codeExample: 'const obj = {\n    name: "Alice",\n    greet: function() {\n        console.log("Hello, " + this.name);\n    },\n    greetArrow: () => {\n        console.log("Hello, " + this.name);  // this is NOT obj\n    }\n};\nobj.greet();  // Hello, Alice\nobj.greetArrow();  // Hello, undefined', keyPoints: ['Depends on how function is called', 'Arrow functions inherit this from parent scope', 'bind/call/apply set this explicitly', 'Event handlers this is the element'], commonMistakes: ['Losing this in callbacks', 'Using arrow functions for object methods'] },
    { term: 'Spread Operator', difficulty: 'Beginner', definition: 'Expand iterables into individual elements with ...', codeExample: 'const arr1 = [1, 2, 3];\nconst arr2 = [4, 5, 6];\nconst merged = [...arr1, ...arr2];  // [1,2,3,4,5,6]\n\nconst obj1 = { a: 1, b: 2 };\nconst obj2 = { c: 3, ...obj1 };  // { c: 3, a: 1, b: 2 }\n\nconst [first, ...rest] = [10, 20, 30, 40];\n// first=10, rest=[20,30,40]', keyPoints: ['Shallow copies arrays and objects', 'Useful for immutable updates', 'Rest parameter collects remaining args', 'Spread in function calls: Math.max(...nums)'] },
    { term: 'Local Storage vs Session Storage', difficulty: 'Beginner', definition: 'Web Storage API for persistent client-side data', codeExample: '// localStorage: persists across tabs and sessions\nlocalStorage.setItem("theme", "dark");\nconst theme = localStorage.getItem("theme");\nlocalStorage.removeItem("theme");\nlocalStorage.clear();\n\n// sessionStorage: cleared when tab closes\nsessionStorage.setItem("temp", "value");', keyPoints: ['Storage limit ~5-10MB', 'Synchronous API', 'Only stores strings (JSON.stringify/parse)', 'localStorage: persists forever', 'sessionStorage: per-tab, cleared on close'], compareWith: 'sessionStorage vs localStorage' },
    { term: 'Fetch API', difficulty: 'Intermediate', definition: 'Modern replacement for XMLHttpRequest for HTTP requests', codeExample: 'async function getData() {\n    try {\n        const res = await fetch("/api/data", {\n            method: "POST",\n            headers: { "Content-Type": "application/json" },\n            body: JSON.stringify({ id: 1 })\n        });\n        if (!res.ok) throw new Error("HTTP " + res.status);\n        const data = await res.json();\n        return data;\n    } catch (err) {\n        console.error("Fetch failed:", err);\n    }\n}', keyPoints: ['Returns Promise<Response>', 'Response.json() parses JSON body', 'HTTP errors do NOT reject - check res.ok', 'AbortController for timeout/cancellation'], commonMistakes: ['Not checking res.ok for HTTP errors', 'Forgetting to await json() parsing'] },
    { term: 'Module System', difficulty: 'Intermediate', definition: 'ES6 import/export for modular code organization', codeExample: '// math.js\nexport const add = (a, b) => a + b;\nexport default function multiply(a, b) { return a * b; }\n\n// app.js\nimport multiply, { add } from "./math.js";\nimport * as math from "./math.js";\nconsole.log(add(2, 3));  // 5\nconsole.log(multiply(2, 3));  // 6', keyPoints: ['Named exports vs default export', 'Import all with * as namespace', 'Static analysis enables tree shaking', 'Dynamic import() for lazy loading'], compareWith: 'CommonJS require vs ES6 import' },
    { term: 'Debouncing vs Throttling', difficulty: 'Advanced', definition: 'Techniques to limit rate of function execution', codeExample: '// Debounce: wait until pause\nfunction debounce(fn, delay) {\n    let timer;\n    return function(...args) {\n        clearTimeout(timer);\n        timer = setTimeout(() => fn.apply(this, args), delay);\n    };\n}\n// Throttle: limit to once per interval\nfunction throttle(fn, limit) {\n    let inThrottle = false;\n    return function(...args) {\n        if (!inThrottle) {\n            fn.apply(this, args);\n            inThrottle = true;\n            setTimeout(() => inThrottle = false, limit);\n        }\n    };\n}', keyPoints: ['Debounce: fires after inactivity', 'Throttle: fires at most once per interval', 'Debounce for search input suggestions', 'Throttle for scroll/resize handlers'], compareWith: 'debounce vs throttle', commonMistakes: ['Using debounce when throttle is needed'] },
    { term: 'Memoization', difficulty: 'Intermediate', definition: 'Caching function results based on arguments', codeExample: 'function memoize(fn) {\n    const cache = new Map();\n    return function(...args) {\n        const key = JSON.stringify(args);\n        if (cache.has(key)) return cache.get(key);\n        const result = fn.apply(this, args);\n        cache.set(key, result);\n        return result;\n    };\n}\nconst fib = memoize(function(n) {\n    if (n <= 1) return n;\n    return fib(n - 1) + fib(n - 2);\n});', keyPoints: ['Trades memory for speed', 'Pure functions work best', 'Map for O(1) lookup', 'Consider cache size limits'], followUps: ['How would you add TTL to memoization?'] },
    { term: 'Prototypal Inheritance', difficulty: 'Advanced', definition: 'Objects inherit from other objects via prototype chain', codeExample: 'const animal = {\n    speak() { console.log(this.sound); }\n};\nconst dog = Object.create(animal);\ndog.sound = "Woof!";\ndog.speak();  // Woof!\n\n// With classes (syntactic sugar)\nclass Animal {\n    constructor(sound) { this.sound = sound; }\n    speak() { console.log(this.sound); }\n}\nclass Dog extends Animal {\n    constructor() { super("Woof!"); }\n}', keyPoints: ['__proto__ vs prototype property', 'Object.create() sets prototype', 'Class syntax is sugar over prototype chain', 'Property lookup walks the chain'], compareWith: 'class-based inheritance in Java' }
  ],
  java: [
    { term: 'Generics', difficulty: 'Intermediate', definition: 'Type parameters enabling type-safe collections and algorithms', codeExample: 'public class Box<T> {\n    private T value;\n    public void set(T value) { this.value = value; }\n    public T get() { return value; }\n}\n// Wildcards\npublic void process(List<? extends Number> nums) { }\npublic void add(List<? super Integer> list) { }', keyPoints: ['Type erasure at runtime', '<? extends T> for producers (read)', '<? super T> for consumers (write)', 'PECS: Producer Extends, Consumer Super'], commonMistakes: ['Cannot use primitives as type parameters', 'Cannot instantiate T directly'] },
    { term: 'Stream API', difficulty: 'Intermediate', definition: 'Functional-style operations on sequences of elements', codeExample: 'List<String> names = Arrays.asList("Alice", "Bob", "Charlie");\nList<String> filtered = names.stream()\n    .filter(n -> n.startsWith("A"))\n    .map(String::toUpperCase)\n    .collect(Collectors.toList());\n// Parallel stream\nint sum = list.parallelStream()\n    .mapToInt(Integer::intValue)\n    .sum();', keyPoints: ['Intermediate ops: filter, map, sorted', 'Terminal ops: collect, forEach, reduce', 'Streams are consumed once', 'parallelStream() for multi-core'], commonMistakes: ['Reusing a consumed stream', 'Not using parallelStream correctly'] },
    { term: 'Optional', difficulty: 'Intermediate', definition: 'Container object to avoid null pointer exceptions', codeExample: 'public Optional<String> findName(int id) {\n    // Return Optional.of() or Optional.empty()\n}\n// Usage\nString name = findName(42)\n    .orElse("Default")\n    .toUpperCase();\n// orElseThrow\nString result = findName(42)\n    .orElseThrow(() -> new NotFoundException("Missing"));', keyPoints: ['Forces handling of absent values', 'map, filter, flatMap on Optional', 'orElse, orElseGet, orElseThrow', 'Not Serializable'], commonMistakes: ['Using get() without checking isPresent()', 'Using Optional for fields or parameters'] },
    { term: 'Multithreading', difficulty: 'Advanced', definition: 'Running multiple threads concurrently in Java', codeExample: '// Runnable\nThread t = new Thread(() -> {\n    System.out.println("Running in thread");\n});\nt.start();\nt.join();\n// ExecutorService\nExecutorService exec = Executors.newFixedThreadPool(4);\nFuture<Integer> future = exec.submit(() -> {\n    return computeExpensive();\n});\nInteger result = future.get(5, TimeUnit.SECONDS);', keyPoints: ['Thread lifecycle: new, runnable, blocked, terminated', 'synchronized keyword for mutual exclusion', 'volatile for visibility', 'ExecutorService for thread pool management'], commonMistakes: ['Deadlocks from nested synchronization', 'Not handling InterruptedException'] },
    { term: 'Reflection', difficulty: 'Advanced', definition: 'Inspecting and modifying runtime behavior of classes', codeExample: 'Class<?> clazz = Class.forName("com.example.User");\nMethod[] methods = clazz.getDeclaredMethods();\nConstructor<?> ctor = clazz.getDeclaredConstructor();\nctor.setAccessible(true);\nObject instance = ctor.newInstance();\nMethod m = clazz.getMethod("getName");\nString name = (String) m.invoke(instance);', keyPoints: ['Performance overhead', 'Breaks encapsulation', 'Used in frameworks (Spring, Hibernate)', 'Can access private fields/methods'] },
    { term: 'Checked vs Unchecked', difficulty: 'Beginner', definition: 'Java exception hierarchy: checked (compile-time) vs unchecked (runtime)', codeExample: '// Checked: must handle or declare\npublic void readFile() throws IOException {\n    FileReader fr = new FileReader("test.txt");\n}\n// Unchecked: RuntimeException\npublic void divide(int a, int b) {\n    if (b == 0) throw new IllegalArgumentException("Div by zero");\n}', keyPoints: ['Checked: IOException, SQLException', 'Unchecked: NullPointerException, IllegalArgumentException', 'Checked must be caught or declared in throws', 'RuntimeException subclasses are unchecked'], compareWith: 'checked vs unchecked exceptions' },
    { term: 'Lambda Expressions', difficulty: 'Intermediate', definition: 'Concise syntax for implementing functional interfaces', codeExample: '// Before: anonymous class\nbutton.addActionListener(new ActionListener() {\n    public void actionPerformed(ActionEvent e) {\n        System.out.println("Clicked");\n    }\n});\n// After: lambda\nbutton.addActionListener(e -> System.out.println("Clicked"));\n\n// Method reference\nlist.forEach(System.out::println);\nlist.stream().map(String::toUpperCase);', keyPoints: ['Functional interface: single abstract method', 'Target typing: inferred from context', 'Method references: Class::method', 'Common functional interfaces: Predicate, Function, Consumer'] },
    { term: 'Annotatations', difficulty: 'Intermediate', definition: 'Metadata tags providing information about code elements', codeExample: '@Retention(RetentionPolicy.RUNTIME)\n@Target(ElementType.METHOD)\npublic @interface LogExecution {\n    String level() default "INFO";\n}\n\n// Usage\npublic class Service {\n    @LogExecution(level = "DEBUG")\n    public void process() { }\n}\n\n// Processing via reflection', keyPoints: ['@Override, @Deprecated, @SuppressWarnings', 'Custom annotations with @interface', 'Retention: SOURCE, CLASS, RUNTIME', 'Target: TYPE, METHOD, FIELD, PARAMETER'] },
    { term: 'CompletableFuture', difficulty: 'Advanced', definition: 'Asynchronous programming with composable futures', codeExample: 'CompletableFuture<String> future =\n    CompletableFuture.supplyAsync(() -> fetchData())\n        .thenApply(data -> process(data))\n        .thenApply(result -> result.toUpperCase())\n        .exceptionally(ex -> "Fallback value");\n\n// Combine two futures\nCompletableFuture<String> combined =\n    future1.thenCombine(future2, (a, b) -> a + b);\n\n// Wait for all\nCompletableFuture.allOf(f1, f2, f3).join();', keyPoints: ['supplyAsync, runAsync for starting', 'thenApply, thenCompose for chaining', 'exceptionally for error recovery', 'allOf, anyOf for combining'], followUps: ['Compare CompletableFuture with reactive streams'] }
  ],
  react: [
    { term: 'JSX', difficulty: 'Beginner', definition: 'JavaScript XML syntax extension for React elements', codeExample: 'function Welcome({ name }) {\n  return (\n    <div className="welcome">\n      <h1>Hello, {name}</h1>\n      {condition && <p>Extra content</p>}\n    </div>\n  );\n}', keyPoints: ['Compiles to React.createElement calls', 'className instead of class', '{} for JS expressions', 'Must have a single root element or <> fragment'] },
    { term: 'Keys in Lists', difficulty: 'Beginner', definition: 'Unique identifiers helping React identify which items changed', codeExample: 'function ItemList({ items }) {\n  return (\n    <ul>\n      {items.map(item => (\n        <li key={item.id}>{item.name}</li>\n      ))}\n    </ul>\n  );\n}', keyPoints: ['Helps with efficient re-rendering', 'Use stable IDs, not array index', 'Keys must be unique among siblings', 'Used for reconciliation algorithm'], commonMistakes: ['Using index as key when list can reorder', 'Not providing key prop'] },
    { term: 'Controlled Components', difficulty: 'Intermediate', definition: 'Form inputs controlled by React state', codeExample: 'function LoginForm() {\n  const [email, setEmail] = useState("");\n  const [password, setPassword] = useState("");\n  \n  const handleSubmit = (e) => {\n    e.preventDefault();\n    console.log("Login:", email, password);\n  };\n  \n  return (\n    <form onSubmit={handleSubmit}>\n      <input value={email}\n             onChange={e => setEmail(e.target.value)} />\n      <input type="password" value={password}\n             onChange={e => setPassword(e.target.value)} />\n      <button type="submit">Login</button>\n    </form>\n  );\n}', keyPoints: ['React state is single source of truth', 'onChange handler updates state', 'Form validation in real-time', 'Easier to test and debug'], compareWith: 'uncontrolled components with refs' },
    { term: 'useRef', difficulty: 'Intermediate', definition: 'Hook that persists mutable values across renders without causing re-renders', codeExample: 'function Timer() {\n  const intervalRef = useRef(null);\n  \n  const startTimer = () => {\n    intervalRef.current = setInterval(() => {\n      console.log("Tick");\n    }, 1000);\n  };\n  \n  const stopTimer = () => {\n    clearInterval(intervalRef.current);\n  };\n  \n  return (\n    <div>\n      <button onClick={startTimer}>Start</button>\n      <button onClick={stopTimer}>Stop</button>\n    </div>\n  );\n}', keyPoints: ['Mutable object with .current', 'Persists across renders', 'Changing does NOT re-render', 'Common for DOM refs and intervals'] },
    { term: 'Context API', difficulty: 'Intermediate', definition: 'Pass data through component tree without manual prop drilling', codeExample: 'const ThemeContext = React.createContext("light");\n\nfunction App() {\n  return (\n    <ThemeContext.Provider value="dark">\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nfunction Toolbar() {\n  const theme = useContext(ThemeContext);\n  return <div className={theme}>Content</div>;\n}', keyPoints: ['Provider/Consumer pattern', 'useContext hook for consuming', 'Can cause unnecessary re-renders', 'Not a replacement for global state management'], commonMistakes: ['Overusing Context for everything', 'Not splitting contexts by domain'] },
    { term: 'Error Boundaries', difficulty: 'Advanced', definition: 'Components catching JavaScript errors in their child tree', codeExample: 'class ErrorBoundary extends React.Component {\n  constructor(props) {\n    super(props);\n    this.state = { hasError: false };\n  }\n  static getDerivedStateFromError(error) {\n    return { hasError: true };\n  }\n  componentDidCatch(error, errorInfo) {\n    logErrorToService(error, errorInfo);\n  }\n  render() {\n    if (this.state.hasError) {\n      return <h1>Something went wrong.</h1>;\n    }\n    return this.props.children;\n  }\n}', keyPoints: ['Only class components can be error boundaries', 'Catches render, lifecycle, and constructor errors', 'Does NOT catch event handler errors', 'getDerivedStateFromError and componentDidCatch'], commonMistakes: ['Using error boundaries in event handlers'] },
    { term: 'Portals', difficulty: 'Intermediate', definition: 'Render children into a different DOM subtree', codeExample: 'function Modal({ isOpen, onClose, children }) {\n  if (!isOpen) return null;\n  return ReactDOM.createPortal(\n    <div className="modal-overlay">\n      <div className="modal-content">\n        <button onClick={onClose}>X</button>\n        {children}\n      </div>\n    </div>,\n    document.getElementById("modal-root")\n  );\n}', keyPoints: ['Renders outside parent DOM hierarchy', 'Events bubble through React tree, not DOM tree', 'Useful for modals, tooltips, dropdowns', 'Accessibility considerations'] },
    { term: 'Higher-Order Components', difficulty: 'Advanced', definition: 'Functions taking a component and returning an enhanced component', codeExample: 'function withAuth(WrappedComponent) {\n  return function AuthenticatedComponent(props) {\n    const { user } = useAuth();\n    if (!user) return <Redirect to="/login" />;\n    return <WrappedComponent {...props} user={user} />;\n  };\n}\n\nconst AdminPage = withAuth(AdminPanel);', keyPoints: ['Pattern for cross-cutting concerns', 'Dont mutate the original component', 'Pass unrelated props through', 'Can compose multiple HOCs'], compareWith: 'HOCs vs Render Props vs Hooks' },
    { term: 'Custom Hooks', difficulty: 'Intermediate', definition: 'Reusable stateful logic extracted into functions using hooks', codeExample: 'function useWindowSize() {\n  const [size, setSize] = useState({\n    width: window.innerWidth,\n    height: window.innerHeight\n  });\n  useEffect(() => {\n    const handleResize = () => {\n      setSize({ width: window.innerWidth, height: window.innerHeight });\n    };\n    window.addEventListener("resize", handleResize);\n    return () => window.removeEventListener("resize", handleResize);\n  }, []);\n  return size;\n}\n\nfunction App() {\n  const { width, height } = useWindowSize();\n  return <div>Window: {width}x{height}</div>;\n}', keyPoints: ['Start with "use" prefix convention', 'Extract repeated logic from components', 'Can call other hooks inside', 'Each instance has isolated state'] }
  ]
};

// Build the insertion data
var courseTopics = {
  python: ['Variables & Data Types', 'Control Flow', 'Functions & Scope', 'Data Structures', 'OOP in Python', 'Advanced Python'],
  javascript: ['Core Concepts', 'DOM & Browser APIs', 'Async JavaScript', 'ES6+ Features', 'Advanced JavaScript', 'Node.js Basics'],
  java: ['Core Java', 'Collections Framework', 'Concurrency', 'JVM & Memory', 'I/O & NIO', 'Modern Java (8+)'],
  react: ['Core React', 'Hooks', 'State Management', 'Performance']
};

// Build replacement: for each course, insert extra concepts before the ]); that closes the topic
var result = src;
Object.keys(extraConcepts).forEach(function(courseId) {
  var concepts = extraConcepts[courseId];
  var topics = courseTopics[courseId];
  // Split concepts among topics: roughly evenly
  var perTopic = Math.ceil(concepts.length / topics.length);
  var idx = 0;
  topics.forEach(function(topicName) {
    var batch = concepts.slice(idx, idx + perTopic);
    idx += perTopic;
    if (batch.length === 0) return;
    // Find the insertion point: after this topic's last concept, before ]);\n            },    
    // Pattern: we look for the topic name followed by concepts array
    var conceptLines = [];
    batch.forEach(function(c) {
      var parts = ['        { term: ' + JSON.stringify(c.term) + ', difficulty: ' + JSON.stringify(c.difficulty)];
      if (c.definition) parts.push('definition: ' + JSON.stringify(c.definition));
      if (c.codeExample) parts.push('codeExample: ' + JSON.stringify(c.codeExample));
      if (c.codeOutput) parts.push('codeOutput: ' + JSON.stringify(c.codeOutput));
      if (c.keyPoints) parts.push('keyPoints: ' + JSON.stringify(c.keyPoints));
      if (c.commonMistakes) parts.push('commonMistakes: ' + JSON.stringify(c.commonMistakes));
      if (c.followUps) parts.push('followUps: ' + JSON.stringify(c.followUps));
      if (c.compareWith) parts.push('compareWith: ' + JSON.stringify(c.compareWith));
      if (c.scenario) parts.push('scenario: ' + JSON.stringify(c.scenario));
      if (c.bugCode) parts.push('bugCode: ' + JSON.stringify(c.bugCode));
      if (c.bugExplanation) parts.push('bugExplanation: ' + JSON.stringify(c.bugExplanation));
      if (c.fixedCode) parts.push('fixedCode: ' + JSON.stringify(c.fixedCode));
      if (c.fixedOutput) parts.push('fixedOutput: ' + JSON.stringify(c.fixedOutput));
      if (c.realWorld) parts.push('realWorld: ' + JSON.stringify(c.realWorld));
      if (c.codeExplanation) parts.push('codeExplanation: ' + JSON.stringify(c.codeExplanation));
      if (c.practice) parts.push('practice: ' + JSON.stringify(c.practice));
      if (c.systemDesign) parts.push('systemDesign: ' + JSON.stringify(c.systemDesign));
      conceptLines.push('        ' + parts.join(',\\n            ') + ' },');
    });
    var insertionText = conceptLines.join('\\n');
    // Insert before the closing ]); of this topic
    // We find the topic in the source and insert before its closing
    var searchPattern = "      { name: '" + topicName.replace(/'/g, "\\'") + "', concepts: [";
    var topicPos = result.indexOf(searchPattern);
    if (topicPos >= 0) {
      var closePattern = '      ]},';
      var closePos = result.indexOf(closePattern, topicPos);
      if (closePos >= 0) {
        result = result.slice(0, closePos) + '\\n' + insertionText + '\\n' + result.slice(closePos);
      }
    }
  });
});

fs.writeFileSync(__dirname + '/interview-data.js', result, 'utf8');
console.log('Expanded interview-data.js written');
