function q(s) {
  return "'" + s.replace(/'/g, "\\'") + "'";
}

function fmt(course, topic, term, diff, defn, code, points) {
  const pts = points.map(p => `'${p.replace(/'/g, "\\'")}'`).join(', ');
  return `addC(${q(course)}, ${q(topic)}, ${q(term)}, ${q(diff)}, ${q(defn)}, { codeExample: ${q(code)}, keyPoints: [${pts}] })`;
}

const data = [
  // ===== python (7) =====
  ['python', 'Variables & Data Types', 'Dynamic Typing', 'Beginner', 'Python determines variable types at runtime, allowing flexible assignment without explicit declarations.', 'x = 10\nx = "hello"  # type changes', ['Types resolved at runtime', 'No explicit declarations needed', 'Enables rapid prototyping']],
  ['python', 'Variables & Data Types', 'Type Casting', 'Beginner', 'Converting a value from one data type to another using built-in functions like int(), str(), and float().', 'x = "42"\ny = int(x) + 8  # 50', ['Use int(), str(), float()', 'Implicit vs explicit casting', 'Can raise ValueError']],
  ['python', 'Control Flow', 'List Comprehensions', 'Intermediate', 'A concise syntax for creating lists by iterating over an iterable with an optional filter condition.', 'squares = [x**2 for x in range(10) if x % 2 == 0]', ['More readable than map/filter', 'Supports nested comprehensions', 'Avoids explicit loops']],
  ['python', 'Functions & Scope', 'Lambda Functions', 'Intermediate', 'Anonymous inline functions defined with the lambda keyword, restricted to a single expression.', 'add = lambda a, b: a + b\nprint(add(3, 4))  # 7', ['Single expression only', 'Often used with map/filter', 'Keeps callbacks concise']],
  ['python', 'Data Structures', 'Dictionary Operations', 'Intermediate', 'Python dictionaries store key-value pairs with O(1) average lookup using hash tables.', 'd = {"alice": 30, "bob": 25}\nd.get("charlie", 0)  # safe access', ['Hash-table backed', 'Keys must be hashable', 'Use .get() for safe access']],
  ['python', 'OOP in Python', 'Decorators', 'Advanced', 'Functions that wrap another function to extend behavior without modifying its source code.', 'def timer(fn):\n    def wrapper(*args):\n        start = time()\n        fn(*args)\n        print(time() - start)\n    return wrapper', ['Syntactic sugar with @', 'Used for logging, caching, auth', 'Can stack multiple decorators']],
  ['python', 'Advanced Python', 'Generators', 'Advanced', 'Functions using yield to produce a sequence of values lazily, preserving state between calls.', 'def fib():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b', ['Lazy evaluation saves memory', 'Supports infinite sequences', 'State persisted across yields']],

  // ===== javascript (7) =====
  ['javascript', 'Core Concepts', 'Closures', 'Intermediate', 'A closure is a function that retains access to its outer scope variables even after the outer function has returned.', 'function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}', ['Preserves lexical scope', 'Enables data privacy', 'Used in callbacks and iterators']],
  ['javascript', 'Core Concepts', 'Hoisting', 'Intermediate', 'JavaScript moves variable and function declarations to the top of their scope before execution.', 'console.log(x);  // undefined\nvar x = 5;', ['var declarations are hoisted', 'let/const are hoisted but not initialized', 'Function declarations fully hoisted']],
  ['javascript', 'DOM & Browser APIs', 'Event Delegation', 'Intermediate', 'Attaching a single listener to a parent element to handle events from its children via bubbling.', 'parent.addEventListener("click", (e) => {\n  if (e.target.matches("li")) handle(e);\n});', ['Reduces memory usage', 'Works on dynamic elements', 'Relies on event bubbling']],
  ['javascript', 'Async JavaScript', 'Promises', 'Intermediate', 'An object representing the eventual completion or failure of an asynchronous operation.', 'fetch("/api")\n  .then(r => r.json())\n  .catch(err => console.error(err));', ['Chains with .then()/.catch()', 'Has three states: pending, fulfilled, rejected', 'Replaces callback hell']],
  ['javascript', 'ES6+ Features', 'Destructuring', 'Intermediate', 'Unpacking values from arrays or properties from objects into distinct variables using a concise syntax.', 'const { name, age } = person;\nconst [first, ...rest] = arr;', ['Works with arrays and objects', 'Supports default values', 'Useful in function parameters']],
  ['javascript', 'Advanced JavaScript', 'Prototypal Inheritance', 'Advanced', 'Objects inherit from other objects via the prototype chain rather than classical class-based inheritance.', 'function Animal(name) { this.name = name; }\nAnimal.prototype.speak = () => "hello";', ['Each object has [[Prototype]]', 'Property lookup walks the chain', 'Can extend with Object.create()']],
  ['javascript', 'Node.js Basics', 'Event Loop', 'Intermediate', 'The mechanism that allows Node.js to perform non-blocking I/O by offloading operations to the system kernel.', 'console.log("1");\nsetTimeout(() => console.log("2"), 0);\nconsole.log("3");  // 1, 3, 2', ['Single-threaded event loop', 'Phases: timers, poll, check', 'setTimeout is not guaranteed delay']],

  // ===== java (7) =====
  ['java', 'Core Java', 'Garbage Collection', 'Intermediate', 'Automatic memory management that reclaims heap objects no longer referenced by the application.', 'System.gc();  // hint to run GC', ['Runs on the JVM', 'Mark-and-sweep algorithm', 'Stop-the-world pauses possible']],
  ['java', 'Collections Framework', 'HashMap Internals', 'Intermediate', 'A hash-table-based Map implementation using buckets and linked lists or trees for collision handling.', 'Map<String, Integer> map = new HashMap<>();\nmap.put("key", 42);', ['O(1) average lookup', 'Uses hashCode() and equals()', 'Resizes when load factor exceeded']],
  ['java', 'Concurrency', 'Synchronized Keyword', 'Intermediate', 'Ensures a method or block is accessed by only one thread at a time using intrinsic locks.', 'synchronized void increment() { count++; }', ['Intrinsic lock per object', 'Reentrant locks', 'Can cause contention']],
  ['java', 'JVM & Memory', 'Stack vs Heap', 'Intermediate', 'The stack stores local variables and method calls per thread, while the heap holds all objects shared across threads.', 'void foo() { int x = 1; }  // x on stack', ['Stack is thread-private', 'Heap is shared', 'Heap requires GC']],
  ['java', 'I/O & NIO', 'Buffered Streams', 'Intermediate', 'Wrapping I/O streams with a buffer to reduce system calls and improve read/write performance.', 'BufferedReader br = new BufferedReader(new FileReader("f.txt"));\nbr.readLine();', ['Reduces disk access', 'Supports line-based reading', 'Must flush and close']],
  ['java', 'Modern Java (8+)', 'Stream API', 'Intermediate', 'A functional-style pipeline for processing sequences of elements with operations like map, filter, and reduce.', 'list.stream()\n    .filter(x -> x > 5)\n    .map(x -> x * 2)\n    .collect(Collectors.toList());', ['Lazy evaluation', 'Can run in parallel', 'Does not modify source']],
  ['java', 'Core Java', 'Exception Hierarchy', 'Beginner', 'Java exceptions inherit from Throwable, divided into checked (compile-time) and unchecked (runtime) categories.', 'try {\n  Files.readString(path);\n} catch (IOException e) {\n  e.printStackTrace();\n}', ['Checked: IOException, SQLException', 'Unchecked: NullPointerException', 'Finally block always executes']],

  // ===== react (7) =====
  ['react', 'Core React', 'JSX', 'Beginner', 'A syntax extension that lets you write HTML-like markup inside JavaScript, transpiled to React.createElement calls.', 'const el = <h1 className="title">Hello</h1>;', ['Not HTML but syntactic sugar', 'Requires Babel transpilation', 'Embeds JS with curly braces']],
  ['react', 'Core React', 'Virtual DOM', 'Intermediate', 'An in-memory representation of the real DOM that React diffs against to minimize actual DOM updates.', '// Happens under the hood\nsetState(() => re-render());', ['Improves performance', 'Uses reconciliation algorithm', 'Batch updates to real DOM']],
  ['react', 'Hooks', 'useState', 'Intermediate', 'A Hook that adds local state to functional components, returning a state variable and its setter.', 'const [count, setCount] = useState(0);', ['Preserves state across renders', 'Setter triggers re-render', 'Initial value only on first render']],
  ['react', 'Hooks', 'useEffect', 'Intermediate', 'A Hook for performing side effects in functional components, running after render by default.', 'useEffect(() => {\n  fetchData().then(setData);\n}, []);', ['Runs after render', 'Dependency array controls execution', 'Return cleanup function']],
  ['react', 'State Management', 'Context API', 'Intermediate', 'A built-in mechanism to share values across the component tree without manually passing props.', 'const ThemeCtx = createContext("light");\nconst value = useContext(ThemeCtx);', ['Avoids prop drilling', 'Not optimized for high-frequency updates', 'Provider wraps subtree']],
  ['react', 'State Management', 'Redux', 'Advanced', 'A predictable state container using a single store, pure reducers, and dispatched actions.', 'const reducer = (state, action) => {\n  switch (action.type) {\n    case "INC": return { ...state, count: state.count + 1 };\n  }\n};', ['Single source of truth', 'State is read-only', 'Changes via pure reducers']],
  ['react', 'Performance', 'React.memo', 'Intermediate', 'A higher-order component that memoizes renders by shallow-comparing props to skip unnecessary updates.', 'const Child = React.memo(({ name }) => <p>{name}</p>);', ['Shallow prop comparison', 'Prevents wasted renders', 'Use with useCallback for functions']],

  // ===== sql (7) =====
  ['sql', 'Query Fundamentals', 'SELECT Statement', 'Beginner', 'Retrieves rows from a table, optionally filtered, sorted, or aggregated using clauses like WHERE and ORDER BY.', 'SELECT name, age FROM users WHERE age > 18 ORDER BY name;', ['Core data retrieval command', 'Supports WHERE, GROUP BY, HAVING', 'ORDER BY sorts results']],
  ['sql', 'Query Fundamentals', 'JOINs', 'Intermediate', 'Combines rows from two or more tables based on a related column, with INNER, LEFT, RIGHT, and FULL variants.', 'SELECT e.name, d.dept\nFROM emp e\nJOIN dept d ON e.dept_id = d.id;', ['INNER returns matching rows', 'LEFT JOIN preserves left table', 'Multiple joins in one query']],
  ['sql', 'Advanced Queries', 'Subqueries', 'Intermediate', 'A query nested inside another query, used in SELECT, FROM, or WHERE clauses to compute intermediate results.', 'SELECT * FROM emp\nWHERE salary > (SELECT AVG(salary) FROM emp);', ['Can be correlated or uncorrelated', 'Used in WHERE, FROM, SELECT', 'Often replaceable with JOIN']],
  ['sql', 'Advanced Queries', 'Window Functions', 'Advanced', 'Functions that perform calculations across a set of rows related to the current row without collapsing them.', 'SELECT name, salary,\n  RANK() OVER (ORDER BY salary DESC) AS rnk\nFROM emp;', ['ROW_NUMBER, RANK, DENSE_RANK', 'PARTITION BY for groups', 'Preserves row granularity']],
  ['sql', 'Optimization & Indexing', 'B-Tree Index', 'Intermediate', 'A balanced-tree index structure that speeds up equality and range queries by reducing disk I/O.', 'CREATE INDEX idx_name ON users(name);', ['O(log n) search time', 'Good for =, >, <, BETWEEN', 'Slows down writes']],
  ['sql', 'Optimization & Indexing', 'Query Execution Plan', 'Advanced', 'A step-by-step plan the database optimizer generates to execute a query, showing index usage and join methods.', 'EXPLAIN ANALYZE SELECT * FROM users WHERE id = 1;', ['Reveals seq scans vs index scans', 'Shows join algorithms', 'Use to identify bottlenecks']],
  ['sql', 'Administration', 'Transactions', 'Intermediate', 'A group of SQL statements executed atomically with ACID guarantees, committed or rolled back as a unit.', 'BEGIN;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nCOMMIT;', ['ACID compliance', 'COMMIT persists changes', 'ROLLBACK undoes the transaction']],

  // ===== html (7) =====
  ['html', 'HTML Basics', 'Semantic Elements', 'Beginner', 'HTML tags that convey meaning about the content they wrap, like <header>, <main>, <article>, and <footer>.', '<header><nav><a href="/">Home</a></nav></header>', ['Improves accessibility', 'Better SEO ranking', 'Easier code readability']],
  ['html', 'HTML Basics', 'Forms', 'Beginner', 'HTML form elements collect user input and submit it to a server using various input types and validation.', '<form action="/submit" method="POST">\n  <input type="email" required>\n  <button type="submit">Send</button>\n</form>', ['Supports GET and POST methods', 'HTML5 validation attributes', 'Enctype for file uploads']],
  ['html', 'HTML Basics', 'Attributes', 'Beginner', 'Extra properties on HTML elements that configure behavior, such as id, class, src, href, and data-* attributes.', '<img src="photo.jpg" alt="Description" loading="lazy">', ['Global vs element-specific', 'data-* for custom data', 'Boolean attributes like disabled']],
  ['html', 'Accessibility & SEO', 'ARIA Roles', 'Intermediate', 'Accessible Rich Internet Application attributes that enhance semantics for screen readers when native HTML is insufficient.', '<div role="button" tabindex="0" aria-label="Close">X</div>', ['Supplements native semantics', 'Use native elements first', 'aria-label, aria-hidden common']],
  ['html', 'Accessibility & SEO', 'Meta Tags', 'Beginner', 'HTML <meta> tags provide structured metadata about the page for browsers, search engines, and social platforms.', '<meta name="description" content="Free tutorials">\n<meta name="viewport" content="width=device-width">', ['description affects SERP snippets', 'viewport for responsive design', 'og: tags for social sharing']],
  ['html', 'Modern HTML Features', 'Canvas API', 'Intermediate', 'An HTML element that provides a bitmap drawing surface for rendering graphics, charts, and game visuals via JavaScript.', 'const ctx = canvas.getContext("2d");\nctx.fillRect(10, 10, 50, 50);', ['Pixel-based drawing', 'No built-in DOM events', 'Used for games and charts']],
  ['html', 'Modern HTML Features', 'Web Components', 'Advanced', 'A suite of browser APIs enabling reusable encapsulated custom elements with Shadow DOM and HTML templates.', 'class MyBtn extends HTMLElement {\n  connectedCallback() { this.innerHTML = "<button>Click</button>"; }\n}\ncustomElements.define("my-btn", MyBtn);', ['Shadow DOM encapsulation', 'Custom elements via API', 'Reusable across frameworks']],

  // ===== css (7) =====
  ['css', 'Layout', 'Flexbox', 'Intermediate', 'A one-dimensional layout model that distributes space along a main axis and aligns items within a flex container.', '.container { display: flex; justify-content: center; align-items: center; }', ['Main and cross axis layout', 'justify-content and align-items', 'Responsive without floats']],
  ['css', 'Layout', 'CSS Grid', 'Intermediate', 'A two-dimensional layout system that divides a page into rows and columns for precise placement of elements.', '.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }', ['Two-dimensional layout', 'Explicit row/column placement', 'fr unit for fractions']],
  ['css', 'Layout', 'Box Model', 'Beginner', 'Every element is a rectangular box composed of content, padding, border, and margin areas.', 'div { width: 100px; padding: 10px; border: 1px solid; margin: 5px; }', ['Content -> Padding -> Border -> Margin', 'box-sizing controls sizing', 'Margin collapse between blocks']],
  ['css', 'Styling & Effects', 'Transitions', 'Intermediate', 'CSS transitions smoothly animate property changes between two states over a specified duration.', '.btn { transition: background-color 0.3s ease; }\n.btn:hover { background: blue; }', ['Animates between states', 'Requires trigger like :hover', 'Property, duration, timing function']],
  ['css', 'Styling & Effects', 'Animations', 'Intermediate', 'CSS animations define keyframe sequences that run, repeat, or loop independently of state changes.', '@keyframes fade {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}\n.box { animation: fade 1s ease-in; }', ['Keyframes define steps', 'animation-name, -duration, -iteration', 'More control than transitions']],
  ['css', 'Advanced CSS', 'Preprocessors', 'Intermediate', 'Tools like Sass and LESS extend CSS with variables, nesting, mixins, and functions compiled to standard CSS.', '$primary: #333;\n.btn { background: $primary; &:hover { opacity: 0.8; } }', ['Variables and nesting', 'Mixins for reusable patterns', 'Requires compilation step']],
  ['css', 'Advanced CSS', 'Custom Properties', 'Intermediate', 'CSS variables defined with -- prefix that hold reusable values and can be dynamically changed at runtime.', ':root { --main-color: #3498db; }\n.box { color: var(--main-color); }', ['Cascade-aware unlike preprocessor vars', 'Changeable via JavaScript', 'Inherit through DOM tree']],

  // ===== git (7) =====
  ['git', 'Version Control', 'Commits', 'Beginner', 'A snapshot of the project at a point in time, identified by a SHA-1 hash with a message describing the change.', 'git add .\ngit commit -m "Fix login bug"', ['SHA-1 hash identifies commit', 'Commit message is required', 'Local operation until push']],
  ['git', 'Version Control', 'Branching', 'Intermediate', 'A lightweight movable pointer to a commit, allowing parallel development lines without affecting the main codebase.', 'git checkout -b feature/new-feature', ['Isolates feature work', 'Branch is just a pointer', 'Default branch is main/master']],
  ['git', 'Version Control', 'Merging', 'Intermediate', 'Combines changes from different branches, creating a merge commit when there is a diverged history.', 'git checkout main\ngit merge feature-branch', ['Fast-forward or 3-way merge', 'Conflicts require manual resolution', 'Preserves branch history']],
  ['git', 'Advanced Git', 'Rebase', 'Advanced', 'Reapplies commits from one branch onto another tip, rewriting history for a linear commit sequence.', 'git checkout feature\ngit rebase main', ['Linear history', 'Rewrites commit SHAs', 'Never rebase public branches']],
  ['git', 'Advanced Git', 'Stash', 'Intermediate', 'Temporarily saves uncommitted changes so you can switch branches or pull updates without losing work.', 'git stash push -m "WIP"\ngit stash pop', ['Stores changes on a stack', 'Includes staged and unstaged', 'Can apply to different branch']],
  ['git', 'Collaboration', 'Pull Requests', 'Intermediate', 'A feature on hosting platforms that proposes changes from a branch, enabling review and discussion before merging.', '# Created on GitHub after git push', ['Facilitates code review', 'Can trigger CI pipelines', 'Squash or merge options']],
  ['git', 'Collaboration', 'Remote Repos', 'Beginner', 'Repositories hosted on a server (e.g., GitHub) that enable team collaboration via push, pull, and fetch operations.', 'git remote add origin https://github.com/user/repo.git\ngit push -u origin main', ['origin is default remote name', 'fetch gets without merging', 'pull = fetch + merge']],

  // ===== docker (7) =====
  ['docker', 'Containerization', 'Images', 'Beginner', 'A lightweight, immutable, read-only template with instructions for creating a container, built from a Dockerfile.', 'docker build -t my-app:latest .', ['Layered file system', 'Built from Dockerfile', 'Stored in registry']],
  ['docker', 'Containerization', 'Containers', 'Beginner', 'A runnable instance of an image, isolated with its own filesystem, network, and process space.', 'docker run -d -p 3000:3000 my-app', ['Ephemeral by default', 'Shares host kernel', 'Isolated from other containers']],
  ['docker', 'Containerization', 'Dockerfile', 'Intermediate', 'A text file with instructions (FROM, RUN, COPY, CMD) to build a Docker image step by step.', 'FROM node:18\nWORKDIR /app\nCOPY . .\nRUN npm install\nCMD ["node", "index.js"]', ['Each instruction is a layer', 'Order affects caching', 'Multi-stage builds reduce size']],
  ['docker', 'Networking', 'Port Mapping', 'Intermediate', 'Maps a port on the host to a port inside the container, making container services accessible externally.', 'docker run -p 8080:80 nginx', ['Host:Container port mapping', 'Required for external access', 'Can map multiple ports']],
  ['docker', 'Networking', 'Bridge Network', 'Intermediate', 'The default Docker network driver that enables containers on the same host to communicate via IP or name.', 'docker network create my-net\ndocker run --net my-net nginx', ['Default network type', 'Automatic DNS resolution', 'Isolated from host network']],
  ['docker', 'Orchestration & Production', 'Docker Compose', 'Intermediate', 'A tool for defining and running multi-container applications using a YAML file with services, networks, and volumes.', 'services:\n  web:\n    build: .\n    ports: ["3000:3000"]', ['Single YAML config', 'Manages multi-container apps', 'docker compose up/down']],
  ['docker', 'Orchestration & Production', 'Volumes', 'Intermediate', 'Persistent storage managed by Docker that survives container restarts and can be shared between containers.', 'docker volume create data\ndocker run -v data:/app/data my-app', ['Persists beyond container life', 'Stored in Docker area', 'Bind mounts for host paths']],

  // ===== dsa (7) =====
  ['dsa', 'Data Structures', 'Arrays', 'Beginner', 'A contiguous block of memory storing elements of the same type, indexed by position for O(1) random access.', 'arr = [3, 1, 4, 1, 5]\narr[2]  # 4', ['O(1) index access', 'Fixed or dynamic size', 'Cache-friendly locality']],
  ['dsa', 'Data Structures', 'Linked Lists', 'Intermediate', 'A linear sequence of nodes where each node stores data and a pointer to the next node, allowing O(1) insertions.', 'class Node:\n  def __init__(self, val):\n    self.val = val\n    self.next = None', ['O(n) search', 'O(1) insertion at head', 'Singly vs doubly linked']],
  ['dsa', 'Algorithms', 'Binary Search', 'Intermediate', 'An efficient O(log n) algorithm that finds a target in a sorted array by repeatedly dividing the search space.', 'def bs(arr, t):\n  l, r = 0, len(arr)-1\n  while l <= r:\n    m = (l+r)//2\n    if arr[m]==t: return m\n    if arr[m]<t: l=m+1\n    else: r=m-1', ['Requires sorted input', 'O(log n) time', 'Iterative or recursive']],
  ['dsa', 'Algorithms', 'Recursion', 'Intermediate', 'A technique where a function calls itself on a smaller subproblem, requiring a base case to terminate.', 'def fact(n):\n  return 1 if n <= 1 else n * fact(n-1)', ['Base case prevents infinite loop', 'Uses call stack', 'Can cause stack overflow']],
  ['dsa', 'Complexity Analysis', 'Big O Notation', 'Intermediate', 'A mathematical notation describing the upper bound of an algorithm growth rate as input size increases.', 'def find(arr, x):  # O(n)\n  for v in arr:\n    if v == x: return True', ['Describes asymptotic behavior', 'Drops constants and lower terms', 'Common: O(1), O(log n), O(n), O(n^2)']],
  ['dsa', 'Complexity Analysis', 'Space Complexity', 'Intermediate', 'The amount of memory an algorithm uses relative to input size, including input, output, and auxiliary space.', 'def dup(arr):  # O(n) space\n  seen = set()\n  for v in arr: seen.add(v)\n  return seen', ['Includes input + auxiliary', 'Stack space for recursion', 'Trade-off with time complexity']],
  ['dsa', 'Problem Solving Strategies', 'Two Pointers', 'Intermediate', 'A technique using two indices that traverse the data structure from different directions to solve problems in place.', 'def pair_sum(arr, t):\n  l, r = 0, len(arr)-1\n  while l < r:\n    s = arr[l] + arr[r]\n    if s == t: return [l, r]\n    if s < t: l += 1\n    else: r -= 1', ['Works on sorted arrays', 'O(n) time, O(1) space', 'Palindromes, container, 3sum']],

  // ===== cpp (7) =====
  ['cpp', 'Core C++', 'Pointers', 'Intermediate', 'Variables that store memory addresses, enabling direct memory manipulation and dynamic allocation.', 'int x = 10;\nint* p = &x;\n*p = 20;  // x is now 20', ['Store memory addresses', 'Dereference with *', 'Pointer arithmetic possible']],
  ['cpp', 'Core C++', 'References', 'Intermediate', 'Aliases for existing variables that must be initialized and cannot be reassigned, offering safer indirection.', 'int x = 10;\nint& ref = x;\nref = 20;  // x is now 20', ['Alias, not a pointer', 'Cannot be null', 'Cannot be reassigned']],
  ['cpp', 'Core C++', 'Virtual Functions', 'Advanced', 'Member functions declared with virtual that enable runtime polymorphism via the vtable mechanism.', 'class Base {\npublic:\n  virtual void speak() { cout << "Base"; }\n};\nclass Derived : public Base {\n  void speak() override { cout << "Derived"; }\n};', ['Enables dynamic dispatch', 'Requires virtual keyword', 'Overrides must match signature']],
  ['cpp', 'Standard Library (STL)', 'Vectors', 'Intermediate', 'A dynamic array that grows automatically, providing O(1) amortized push_back and contiguous storage.', 'std::vector<int> v = {1, 2, 3};\nv.push_back(4);', ['Contiguous memory', 'Amortized O(1) push', 'Resizes by doubling']],
  ['cpp', 'Standard Library (STL)', 'Iterators', 'Intermediate', 'Objects that abstract pointer-like traversal over STL containers, providing uniform element access.', 'for (auto it = v.begin(); it != v.end(); ++it) {\n  cout << *it;\n}', ['Categories: input, output, fwd, bidir, random', 'Compatible with algorithms', 'Range-for uses iterators']],
  ['cpp', 'Memory & Performance', 'RAII', 'Advanced', 'Resource Acquisition Is Initialization binds resource lifecycle to object lifetime, ensuring automatic cleanup.', 'class File {\n  FILE* f;\npublic:\n  File(const char* n) { f = fopen(n, "r"); }\n  ~File() { if (f) fclose(f); }\n};', ['Resources tied to scope', 'No manual cleanup needed', 'Exception-safe']],
  ['cpp', 'Memory & Performance', 'Smart Pointers', 'Advanced', 'RAII wrappers like unique_ptr and shared_ptr that automatically manage dynamic memory with ownership semantics.', 'auto p = std::make_unique<int>(42);\nauto s = std::make_shared<int>(42);', ['unique_ptr: exclusive ownership', 'shared_ptr: reference counted', 'Avoids raw new/delete']],

  // ===== typescript (7) =====
  ['typescript', 'Type System', 'Interfaces', 'Beginner', 'A TypeScript construct that defines the shape of an object by specifying property names and their types.', 'interface User {\n  name: string;\n  age: number;\n}\nconst u: User = { name: "Alice", age: 30 };', ['Describes object shapes', 'Can be extended', 'Supports optional ? properties']],
  ['typescript', 'Type System', 'Generics', 'Intermediate', 'A way to create reusable components that work with multiple types while preserving type safety.', 'function identity<T>(arg: T): T { return arg; }\nconst n = identity<number>(42);', ['Preserves type information', 'Constraints with extends', 'Used in collections and utilities']],
  ['typescript', 'Type System', 'Union Types', 'Intermediate', 'A type formed from two or more types, allowing a value to be one of several possibilities using |.', 'function format(id: string | number) {\n  return id.toString();\n}', ['Value must be one of the types', 'Narrow with typeof or in', 'Discriminated unions with literals']],
  ['typescript', 'Advanced Types', 'Mapped Types', 'Advanced', 'A type that transforms an existing type by iterating over its keys, often used with keyof and index signatures.', 'type Readonly<T> = {\n  readonly [K in keyof T]: T[K];\n};\ntype ReadonlyUser = Readonly<User>;', ['Iterates with in keyof', 'Maps property modifiers', 'Creates Partial, Required, Pick']],
  ['typescript', 'Advanced Types', 'Conditional Types', 'Advanced', 'A type that selects one of two possible types based on a condition expressed with the extends keyword.', 'type IsString<T> = T extends string ? "yes" : "no";\ntype A = IsString<"hello">;  // "yes"', ['T extends U ? X : Y', 'Distributes over unions', 'Used with infer for extraction']],
  ['typescript', 'Tooling & Configuration', 'tsconfig.json', 'Intermediate', 'The configuration file that controls compiler options, strictness, target ECMAScript version, and module resolution.', '{\n  "compilerOptions": {\n    "strict": true,\n    "target": "ES2020",\n    "module": "ESNext"\n  }\n}', ['Controls compiler behavior', 'strict enables full checking', 'paths for alias mapping']],
  ['typescript', 'Tooling & Configuration', 'Declaration Files', 'Intermediate', 'Files with .d.ts extension that describe the shape of JavaScript modules to TypeScript without implementation.', 'declare module "my-lib" {\n  export function greet(name: string): void;\n}', ['Ambient type declarations', 'No implementation code', 'Used for JS library types']],

  // ===== go (7) =====
  ['go', 'Concurrency', 'Goroutines', 'Intermediate', 'Lightweight threads managed by the Go runtime that execute functions concurrently with minimal overhead.', 'go func() {\n  fmt.Println("hello from goroutine")\n}()', ['Starts with go keyword', 'Stack starts at 2KB', 'M multiplexed onto OS threads']],
  ['go', 'Concurrency', 'Channels', 'Intermediate', 'Typed conduits for communication between goroutines, supporting send, receive, and optional buffering.', 'ch := make(chan int)\nch <- 42\nv := <-ch', ['Synchronize goroutines', 'Unbuffered blocks until both ready', 'Buffered channels non-blocking up to cap']],
  ['go', 'Concurrency', 'Select Statement', 'Advanced', 'A control structure that waits on multiple channel operations, executing the first one that becomes ready.', 'select {\ncase msg := <-ch1:\n  fmt.Println(msg)\ncase <-ch2:\n  fmt.Println("timeout")\ndefault:\n  fmt.Println("no activity")\n}', ['Similar to switch for channels', 'Picks randomly if multiple ready', 'default for non-blocking']],
  ['go', 'Language Features', 'Defer', 'Intermediate', 'A keyword that schedules a function call to run when the surrounding function returns, typically for cleanup.', 'f, _ := os.Open("file.txt")\ndefer f.Close()', ['Executes at return', 'LIFO order for multiple defers', 'Useful for resource release']],
  ['go', 'Language Features', 'Structs', 'Beginner', 'A composite data type grouping named fields of different types, similar to classes without inheritance.', 'type Person struct {\n  Name string\n  Age  int\n}\np := Person{Name: "Alice", Age: 30}', ['Value type by default', 'Methods attached with receivers', 'No inheritance, use composition']],
  ['go', 'Standard Library', 'HTTP Server', 'Intermediate', 'Go net/http package provides a built-in HTTP server with routing, middleware, and templating support.', 'http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {\n  fmt.Fprintf(w, "Hello")\n})\nhttp.ListenAndServe(":8080", nil)', ['Built-in HTTP server', 'DefaultServeMux for routing', 'No external dependencies']],
  ['go', 'Standard Library', 'JSON Handling', 'Intermediate', 'Encoding/json package provides marshaling and unmarshaling between Go structs and JSON data.', 'type User struct { Name string `json:"name"` }\ndata, _ := json.Marshal(user)\nvar u User\njson.Unmarshal(data, &u)', ['Struct tags for field mapping', 'Marshal/Unmarshal', 'Supports custom encoders']],

  // ===== rust (7) =====
  ['rust', 'Ownership & Borrowing', 'Ownership Rules', 'Intermediate', 'Each value in Rust has exactly one owner, and the value is dropped when the owner goes out of scope.', 'let s = String::from("hello");\nlet s2 = s;  // s moved, invalid\n// println!("{}", s);  // error', ['One owner per value', 'Move transfers ownership', 'Copy trait for stack types']],
  ['rust', 'Ownership & Borrowing', 'Borrowing', 'Intermediate', 'Taking a reference to a value without taking ownership, allowing read-only or mutable access under strict rules.', 'fn len(s: &String) -> usize { s.len() }\nlet s = String::from("hi");\nlet l = len(&s);  // borrow, not move', ['Immutable references &T', 'Mutable references &mut T', 'Only one mutable borrow at a time']],
  ['rust', 'Ownership & Borrowing', 'Lifetimes', 'Advanced', 'Annotations that tell the compiler how long references are valid, preventing dangling references at compile time.', 'fn longest<\'a>(x: &\'a str, y: &\'a str) -> &\'a str {\n  if x.len() > y.len() { x } else { y }\n}', ['Elision rules cover common patterns', '\'static for program duration', 'Generic lifetime parameters']],
  ['rust', 'Language Features', 'Pattern Matching', 'Intermediate', 'Rust match expression with exhaustive arm checking, supporting destructuring, guards, and binding modes.', 'match value {\n  1 => println!("one"),\n  2 | 3 => println!("two or three"),\n  _ => println!("other"),\n}', ['Must be exhaustive', 'Arms can have guards', 'Destructures enums and structs']],
  ['rust', 'Language Features', 'Enums', 'Intermediate', 'A type that can be one of several variants, optionally carrying data, enabling expressive and safe APIs.', 'enum Result<T, E> {\n  Ok(T),\n  Err(E),\n}', ['Algebraic data types', 'match forces handling', 'Option and Result are built-in']],
  ['rust', 'Memory Safety', 'No Null', 'Intermediate', 'Rust eliminates null pointer errors by using Option<T> for optional values, forcing explicit handling.', 'fn find_user(id: u32) -> Option<User> {\n  if id == 0 { None } else { Some(User {}) }\n}', ['Option<T> instead of null', 'Null safety at compile time', 'unwrap() or pattern matching']],
  ['rust', 'Memory Safety', 'Trait Bounds', 'Advanced', 'Constraints on generic types specifying which traits must be implemented, enabling compile-time polymorphism.', 'fn print<T: Display>(val: T) {\n  println!("{}", val);\n}', ['Generic constraints', 'Trait bounds with +', 'where clause for readability']],

  // ===== mysql (7) =====
  ['mysql', 'Database Design', 'Normalization', 'Intermediate', 'The process of organizing data to reduce redundancy and dependency by dividing tables and defining relationships.', '-- 1NF: atomic columns\n-- 2NF: no partial dependencies\n-- 3NF: no transitive dependencies', ['1NF, 2NF, 3NF, BCNF', 'Reduces data duplication', 'May require JOINs for queries']],
  ['mysql', 'Database Design', 'Primary Keys', 'Beginner', 'A column or combination of columns that uniquely identifies each row in a table, enforcing entity integrity.', 'CREATE TABLE users (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  email VARCHAR(255) UNIQUE\n);', ['Must be unique and NOT NULL', 'Often integer with AUTO_INCREMENT', 'Natural vs surrogate keys']],
  ['mysql', 'Database Design', 'Foreign Keys', 'Beginner', 'A column that references a primary key in another table, enforcing referential integrity across tables.', 'CREATE TABLE orders (\n  id INT PRIMARY KEY,\n  user_id INT,\n  FOREIGN KEY (user_id) REFERENCES users(id)\n);', ['Enforces referential integrity', 'CASCADE, SET NULL options', 'Indexed automatically in some engines']],
  ['mysql', 'Querying', 'GROUP BY', 'Intermediate', 'Groups rows with the same values into summary rows, often used with aggregate functions like COUNT and SUM.', 'SELECT dept, COUNT(*) FROM emp GROUP BY dept;\nSELECT dept, AVG(salary) FROM emp GROUP BY dept;', ['Groups rows by column values', 'Used with aggregate functions', 'HAVING filters groups']],
  ['mysql', 'Querying', 'Indexed Queries', 'Intermediate', 'Queries that leverage indexes to avoid full table scans, significantly improving read performance.', 'EXPLAIN SELECT * FROM users WHERE email = "a@b.com";\n-- Look for "type: ref" or "const"', ['Index speeds up WHERE/JOIN/ORDER BY', 'Composite index column order matters', 'Too many indexes slow writes']],
  ['mysql', 'Administration', 'User Privileges', 'Intermediate', 'Granular permissions controlling what database operations each user can perform on specific objects.', 'CREATE USER "app"@"%" IDENTIFIED BY "pass";\nGRANT SELECT, INSERT ON mydb.* TO "app"@"%";', ['Global, database, table, column levels', 'FLUSH PRIVILEGES grants cache', 'REVOKE removes permissions']],
  ['mysql', 'Administration', 'Backup & Restore', 'Intermediate', 'Using mysqldump to export logical backups and mysql to restore them, supporting full and point-in-time recovery.', 'mysqldump -u root mydb > backup.sql\nmysql -u root mydb < backup.sql', ['mysqldump for logical backup', '--single-transaction for InnoDB', 'Binary logs for PITR']],

  // ===== linux (7) =====
  ['linux', 'System Administration', 'File Permissions', 'Beginner', 'A permission system with read, write, and execute rights for owner, group, and others, viewed with ls -l.', 'chmod 755 script.sh\nchown user:group file.txt', ['rwx for owner/group/others', 'Octal notation (755, 644)', 'umask sets default permissions']],
  ['linux', 'System Administration', 'Process Management', 'Intermediate', 'Tools and signals for controlling running processes, including ps, top, kill, and background job control.', 'ps aux | grep nginx\nkill -9 1234  # SIGKILL', ['PID uniquely identifies process', 'SIGTERM vs SIGKILL', 'htop for interactive monitoring']],
  ['linux', 'System Administration', 'Package Managers', 'Intermediate', 'Tools like apt, yum, and pacman that install, update, and remove software packages from repositories.', 'sudo apt update\nsudo apt install nginx', ['Resolves dependencies', 'Repositories in sources.list', 'Upgrade all with apt upgrade']],
  ['linux', 'Networking', 'SSH', 'Intermediate', 'Secure Shell protocol for encrypted remote login and command execution over an insecure network.', 'ssh -i key.pem user@hostname\nscp file.txt user@host:/dest', ['Encrypted connection', 'Key-based authentication', 'Port forwarding with -L']],
  ['linux', 'Networking', 'Firewall', 'Intermediate', 'Software like iptables or ufw that controls incoming and outgoing network traffic based on rules.', 'sudo ufw allow 22/tcp\nsudo ufw enable', ['Default deny policy', 'Stateful packet filtering', 'Rules are order-dependent']],
  ['linux', 'Shell Scripting', 'Variables', 'Beginner', 'Named storage locations in shell scripts assigned with = and accessed with $ prefix, scoped by default.', 'NAME="world"\necho "Hello, $NAME"', ['No spaces around =', '${VAR} for unambiguous use', 'export for environment vars']],
  ['linux', 'Shell Scripting', 'Pipelines', 'Intermediate', 'Chaining commands with | so the stdout of one becomes the stdin of the next for data processing.', 'cat access.log | grep "404" | sort | uniq -c | sort -rn', ['Connects stdout to stdin', 'Exit status is last command', 'tee to capture intermediate output']],

  // ===== mongodb (7) =====
  ['mongodb', 'NoSQL Concepts', 'Document Model', 'Beginner', 'MongoDB stores data as BSON documents, which are JSON-like structures with dynamic schemas nested inside collections.', '{\n  "_id": ObjectId("..."),\n  "name": "Alice",\n  "address": { "city": "NYC" }\n}', ['BSON format', 'Dynamic schema', 'Nested subdocuments']],
  ['mongodb', 'NoSQL Concepts', 'Collections', 'Beginner', 'A grouping of MongoDB documents analogous to a table in relational databases, but without enforced schema.', 'db.users.insertOne({ name: "Alice" })\ndb.users.find()', ['Schemaless by design', 'Documents in same collection can differ', 'Indexed for performance']],
  ['mongodb', 'NoSQL Concepts', 'Embedding vs Referencing', 'Intermediate', 'A design decision between nesting related data inside a document or linking via references across collections.', '// Embedding: order contains items[]\n// Referencing: order has user_id ref', ['Embedding for one-to-few', 'Referencing for many-to-many', 'Embedding avoids JOINs']],
  ['mongodb', 'Schema Design', 'Indexes', 'Intermediate', 'Data structures that improve query performance by allowing the database to locate documents without scanning.', 'db.users.createIndex({ email: 1 })', ['B-tree indexes', 'Compound indexes for multiple fields', 'TTL indexes for expiration']],
  ['mongodb', 'Schema Design', 'Aggregation Pipeline', 'Intermediate', 'A framework for data processing with stages like $match, $group, $sort, and $project that transform documents.', 'db.orders.aggregate([\n  { $match: { status: "shipped" } },\n  { $group: { _id: "$cust_id", total: { $sum: "$amount" } } }\n])', ['Pipeline of stages', '$lookup for joins', 'Similar to map-reduce']],
  ['mongodb', 'Operations', 'Replication', 'Advanced', 'A replica set maintains multiple copies of data across servers for high availability and automatic failover.', '# Primary handles writes, secondaries replicate', ['Minimum 3 members', 'Automatic failover', 'Read from secondaries optionally']],
  ['mongodb', 'Operations', 'Sharding', 'Advanced', 'Horizontal scaling strategy that distributes data across multiple servers using a shard key for partitioning.', '# Shard key determines data distribution', ['Horizontal scaling of writes', 'Shard key is critical', 'Config servers track metadata']],

  // ===== c (7) =====
  ['c', 'Memory Management', 'malloc', 'Intermediate', 'Allocates a specified number of bytes on the heap at runtime, returning a void pointer to the allocated memory.', 'int* arr = (int*)malloc(10 * sizeof(int));\nif (arr != NULL) { /* use */ free(arr); }', ['Returns void* on heap', 'Must check for NULL', 'Paired with free()']],
  ['c', 'Memory Management', 'Memory Leaks', 'Intermediate', 'A situation where allocated heap memory is no longer referenced but never freed, gradually consuming resources.', 'void leak() {\n  int* p = (int*)malloc(100);\n  // missing free(p)\n}', ['Occurs when free() is omitted', 'Valgrind detects leaks', 'Each malloc must have matching free']],
  ['c', 'Memory Management', 'Stack vs Heap', 'Intermediate', 'Stack provides automatic allocation and deallocation for local variables, while heap requires manual management.', 'int stackVar = 5;           // stack\nint* heapVar = malloc(4);   // heap', ['Stack is fast and scoped', 'Heap is larger but slower', 'Stack overflow from deep recursion']],
  ['c', 'Pointer & Function Concepts', 'Function Pointers', 'Advanced', 'Variables that store the address of a function, enabling callbacks and dynamic dispatch in C.', 'int add(int a, int b) { return a + b; }\nint (*op)(int, int) = &add;\nint result = op(3, 4);', ['Type includes parameter types', 'Used for callbacks (qsort)', 'Array of function pointers for dispatch']],
  ['c', 'Pointer & Function Concepts', 'Pointer Arithmetic', 'Intermediate', 'Performing arithmetic on pointers shifts the address by multiples of the pointed-to type size.', 'int arr[5] = {10, 20, 30, 40, 50};\nint* p = arr;\n*(p + 2) == arr[2];  // 30', ['Adds sizeof(type) * offset', 'Can iterate through arrays', 'Must stay within bounds']],
  ['c', 'Preprocessor & Compilation', 'Macros', 'Intermediate', 'Preprocessor directives that perform text substitution before compilation, often used for constants and inline code.', '#define PI 3.14159\n#define MAX(a, b) ((a) > (b) ? (a) : (b))', ['Text substitution by preprocessor', 'No type checking', 'Parenthesize arguments to avoid bugs']],
  ['c', 'Preprocessor & Compilation', 'Header Guards', 'Beginner', 'A preprocessing technique using #ifndef/#define/#endif to prevent a header file from being included multiple times.', '#ifndef MY_HEADER_H\n#define MY_HEADER_H\nvoid myFunc();\n#endif', ['Prevents double inclusion', 'Alternative: #pragma once', 'Standard C/C++ practice']],

  // ===== csharp (7) =====
  ['csharp', '.NET Framework', 'CLR', 'Intermediate', 'The Common Language Runtime manages .NET code execution with JIT compilation, garbage collection, and type safety.', '// C# code compiles to IL, CLR JITs it', ['JIT compilation to native', 'GC manages memory', 'Common type system (CTS)']],
  ['csharp', '.NET Framework', 'Garbage Collection', 'Intermediate', 'Automatic memory management in .NET that reclaims objects in generations, handling allocation and cleanup.', 'GC.Collect();  // force collection (rarely needed)', ['3 generations (0, 1, 2)', 'Large object heap', 'Non-deterministic cleanup']],
  ['csharp', '.NET Framework', 'Assemblies', 'Intermediate', 'Compiled .NET units (.dll or .exe) containing IL code, metadata, and resources for deployment and versioning.', '// Project builds to assembly.dll', ['Contains IL and metadata', 'Strong naming for GAC', 'Self-describing manifest']],
  ['csharp', 'C# Language Features', 'Properties', 'Beginner', 'Members that provide a flexible mechanism to read, write, or compute field values with get and set accessors.', 'public class Person {\n  public string Name { get; set; }\n  public int Age { get; private set; }\n}', ['Encapsulate fields', 'Auto-implemented properties', 'Can add validation in setter']],
  ['csharp', 'C# Language Features', 'LINQ', 'Intermediate', 'Language Integrated Query provides SQL-like query syntax over collections, databases, and XML with deferred execution.', 'var adults = from p in persons\n              where p.Age >= 18\n              select p.Name;', ['Works with IEnumerable<T>', 'Deferred execution', 'Method syntax also available']],
  ['csharp', '.NET Ecosystem', 'NuGet', 'Beginner', 'The package manager for .NET providing access to a central repository of libraries and tools.', 'dotnet add package Newtonsoft.Json', ['Central package repository', 'Dependency resolution', 'dotnet CLI integration']],
  ['csharp', '.NET Ecosystem', 'ASP.NET Core', 'Intermediate', 'A cross-platform framework for building web APIs, MVC apps, and microservices with built-in DI and middleware.', 'var app = WebApplication.Create(args);\napp.MapGet("/", () => "Hello");\napp.Run();', ['Cross-platform', 'Built-in DI container', 'Middleware pipeline']],

  // ===== kotlin (7) =====
  ['kotlin', 'Kotlin Features', 'Null Safety', 'Intermediate', 'Kotlin distinguishes nullable (Type?) and non-null types at compile time, preventing null pointer exceptions.', 'var name: String? = null\nval len = name?.length ?: 0', ['? for nullable types', '?. safe call operator', '?: Elvis operator for default']],
  ['kotlin', 'Kotlin Features', 'Data Classes', 'Intermediate', 'Classes with the data keyword that automatically generate equals, hashCode, toString, copy, and component functions.', 'data class User(val name: String, val age: Int)\nval u = User("Alice", 30)', ['Auto-generates common methods', 'copy() for immutable copies', 'Destructuring declarations']],
  ['kotlin', 'Kotlin Features', 'Extension Functions', 'Intermediate', 'Functions that add new behavior to existing classes without inheritance or modifying source code.', 'fun String.isEmail(): Boolean = this.contains("@")\nprintln("a@b.com".isEmail())', ['Add methods to existing classes', 'Static dispatch at compile time', 'Cannot access private members']],
  ['kotlin', 'Interop & Tooling', 'Java Interop', 'Intermediate', 'Kotlin fully interoperates with Java, allowing mixed projects where Kotlin and Java call each other seamlessly.', '// Kotlin calls Java\nval list = ArrayList<String>()\nlist.add("item")', ['100% compatible', 'Use @JvmStatic for static methods', 'Platform types for nullability']],
  ['kotlin', 'Interop & Tooling', 'Coroutines', 'Advanced', 'Lightweight concurrency primitives that suspend execution without blocking threads, using suspend functions.', 'suspend fun fetchData(): String {\n  delay(1000)\n  return "data"\n}\nlaunch { val d = fetchData() }', ['Suspending not blocking', 'Run on Dispatchers', 'Structured concurrency']],
  ['kotlin', 'Standard Library', 'Collections', 'Beginner', 'Kotlin standard library provides immutable and mutable collections with functional extensions like map and filter.', 'val nums = listOf(1, 2, 3, 4)\nval evens = nums.filter { it % 2 == 0 }', ['Mutable vs immutable interfaces', 'Functional extension functions', 'Sequences for lazy evaluation']],
  ['kotlin', 'Standard Library', 'Scope Functions', 'Intermediate', 'Functions like let, apply, run, with, and also that execute code within a context object scope.', 'val result = person.let {\n  "${it.name} is ${it.age}"\n}', ['let returns lambda result', 'apply configures and returns object', 'run combines let and with']],

  // ===== swift (7) =====
  ['swift', 'Swift Features', 'Optionals', 'Intermediate', 'A Swift type that can hold either a value or nil, forcing explicit unwrapping via optional binding or forced unwrap.', 'var name: String? = "Alice"\nif let n = name { print(n) }', ['Wrapped type with ? suffix', 'if let and guard let unwrapping', 'Optional chaining with ?.']],
  ['swift', 'Swift Features', 'Structs vs Classes', 'Intermediate', 'Structs are value types copied on assignment, while classes are reference types with identity and inheritance.', 'struct Point { var x, y: Double }\nclass Animal { var name: String = "" }', ['Structs passed by value', 'Classes passed by reference', 'Structs have no inheritance']],
  ['swift', 'Swift Features', 'Protocols', 'Intermediate', 'A blueprint of methods, properties, and requirements that types can conform to, similar to interfaces.', 'protocol Drawable {\n  func draw()\n}\nstruct Circle: Drawable {\n  func draw() { print("circle") }\n}', ['Adopted by struct/class/enum', 'Protocol extensions provide defaults', 'Generics with protocol constraints']],
  ['swift', 'iOS Development Basics', 'Auto Layout', 'Beginner', 'A constraint-based layout system that dynamically calculates view sizes and positions relative to other views.', 'NSLayoutConstraint.activate([\n  view.topAnchor.constraint(equalTo: parent.topAnchor)\n])', ['Constraint-based positioning', 'Adapts to screen sizes', 'Stack views simplify layout']],
  ['swift', 'iOS Development Basics', 'UIKit', 'Intermediate', 'The iOS framework providing UI components like UIView, UIViewController, UITableView, and event handling.', 'class MyVC: UIViewController {\n  override func viewDidLoad() {\n    view.backgroundColor = .white\n  }\n}', ['View controller lifecycle', 'Event-driven with target-action', 'Storyboard or programmatic UI']],
  ['swift', 'Concurrency & Memory', 'ARC', 'Advanced', 'Automatic Reference Counting manages memory by tracking strong references and deallocating when count reaches zero.', 'weak var delegate: MyDelegate?\nunowned var parent: ParentClass', ['Strong by default', 'weak for optional references', 'unowned for non-optional references']],
  ['swift', 'Concurrency & Memory', 'async/await', 'Advanced', 'Swift structured concurrency model using async functions and await to write asynchronous code sequentially.', 'func fetchData() async -> Data {\n  let url = URL(string: "https://api.example.com")!\n  let (data, _) = try await URLSession.shared.data(from: url)\n  return data\n}', ['Structured concurrency', 'Suspension points with await', 'Task and TaskGroup for parallelism']],

  // ===== pandas (7) =====
  ['pandas', 'Data Manipulation', 'DataFrame', 'Beginner', 'A two-dimensional labeled data structure with columns of potentially different types, similar to a spreadsheet.', 'import pandas as pd\ndf = pd.DataFrame({"name": ["A"], "age": [25]})', ['Rows and columns with labels', 'Handles missing data with NaN', 'Column access with df["col"]']],
  ['pandas', 'Data Manipulation', 'GroupBy', 'Intermediate', 'Split-apply-combine operation that groups rows by a key and applies aggregation functions to each group.', 'df.groupby("dept")["salary"].mean()', ['Split, apply, combine pattern', 'Multiple aggregate functions', 'Can group by multiple columns']],
  ['pandas', 'Data Manipulation', 'Merge/Join', 'Intermediate', 'Combining DataFrames by aligning rows based on common columns or indices, similar to SQL JOINs.', 'pd.merge(df1, df2, on="id", how="left")', ['Inner, outer, left, right joins', 'Can merge on index', 'Suffixes for overlapping columns']],
  ['pandas', 'Analysis & Visualization', 'Plotting', 'Intermediate', 'Built-in plotting based on matplotlib for creating line, bar, scatter, and histogram plots directly from DataFrames.', 'df.plot(kind="bar", x="cat", y="val")', ['Built-in matplotlib integration', 'Kind: bar, line, scatter, hist', 'Customizable with matplotlib']],
  ['pandas', 'Analysis & Visualization', 'Statistical Methods', 'Intermediate', 'Describe, correlation, and other statistical functions that provide quick insights into data distributions.', 'df.describe()\ndf.corr()', ['describe() for summary stats', 'corr() for pairwise correlation', 'Handles NaN automatically']],
  ['pandas', 'Performance & Best Practices', 'Vectorization', 'Advanced', 'Applying operations to entire columns without explicit loops, leveraging NumPy under the hood for speed.', 'df["double"] = df["val"] * 2  # faster than iterrows()', ['Avoids Python loops', 'Operates on entire series', 'Significantly faster than iterrows']],
  ['pandas', 'Performance & Best Practices', 'Memory Optimization', 'Advanced', 'Techniques to reduce DataFrame memory by downcasting numeric types and using categorical dtypes.', 'df["col"] = df["col"].astype("int32")\ndf["cat"] = df["cat"].astype("category")', ['Downcast float/int types', 'Categorical for repeated strings', 'Use chunksize for large files']],

  // ===== security (7) =====
  ['security', 'Authentication & Authorization', 'JWT', 'Intermediate', 'JSON Web Token is a compact, self-contained token format for securely transmitting claims between parties as a JSON object.', '// Header.Payload.Signature\neyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMifQ.ZA', ['Stateless authentication', 'Contains claims in payload', 'Signed to prevent tampering']],
  ['security', 'Authentication & Authorization', 'OAuth 2.0', 'Advanced', 'An authorization framework that grants third-party apps limited access to resources without sharing credentials.', '# Authorization code flow: /auth -> /callback -> tokens', ['Delegated authorization', 'Access and refresh tokens', 'Scopes limit permissions']],
  ['security', 'Authentication & Authorization', 'Session Management', 'Intermediate', 'Server-side storage of authenticated user state identified by a cookie-session ID pair.', 'req.session.userId = user.id;\n// Server stores session data', ['Server-side state', 'Session ID in cookie', 'Expire or rotate sessions']],
  ['security', 'Web Security', 'XSS', 'Intermediate', 'Cross-Site Scripting injects malicious scripts into web pages viewed by others, often via unsanitized input.', '// Bad: innerHTML = userInput\n// Good: textContent = userInput', ['Stored, reflected, DOM-based', 'Sanitize and escape output', 'CSP mitigates impact']],
  ['security', 'Web Security', 'CSRF', 'Intermediate', 'Cross-Site Request Forgery tricks authenticated users into performing unintended actions by crafting malicious requests.', '// Use anti-CSRF token in forms\n// SameSite cookie attribute', ['Exploits user session', 'Anti-CSRF token required', 'SameSite=Strict helps']],
  ['security', 'Cryptography & Network Security', 'HTTPS', 'Intermediate', 'HTTP over TLS encrypts all communication between client and server, preventing eavesdropping and tampering.', 'https://example.com\n// TLS handshake before HTTP', ['Encrypts all traffic', 'Certificate validation', 'TLS 1.3 is current standard']],
  ['security', 'Cryptography & Network Security', 'Hashing vs Encryption', 'Intermediate', 'Hashing is a one-way function for integrity checking, while encryption is two-way for confidentiality.', '// Hash: bcrypt(password) -- cannot reverse\n// Encrypt: AES(data, key) -- can decrypt', ['Hashing is one-way', 'Encryption is reversible', 'Hashing for passwords, encryption for data']],

  // ===== dbms (7) =====
  ['dbms', 'Database Design & Modeling', 'ER Diagrams', 'Beginner', 'Entity-Relationship diagrams visually represent database entities, their attributes, and relationships between them.', '// [Customer] --1:N--> [Order] --N:1--> [Product]', ['Entities as rectangles', 'Relationships as diamonds', 'Cardinality: 1:1, 1:N, N:M']],
  ['dbms', 'Database Design & Modeling', 'Normalization', 'Intermediate', 'A systematic approach to eliminate data redundancy through progressive normal forms up to BCNF.', '-- 1NF: atomic columns\n-- 2NF: remove partial dependencies\n-- 3NF: remove transitive dependencies', ['Reduces update anomalies', 'Increases join complexity', 'Denormalize for read-heavy workloads']],
  ['dbms', 'Database Design & Modeling', 'Keys', 'Beginner', 'Attributes that uniquely identify records, enforce relationships, and maintain integrity across database tables.', '-- Primary Key, Foreign Key, Candidate Key, Super Key', ['PK uniquely identifies a row', 'FK references another table', 'Composite keys use multiple columns']],
  ['dbms', 'Transaction Management', 'ACID Properties', 'Intermediate', 'Atomicity, Consistency, Isolation, Durability guarantee reliable transaction processing in database systems.', '-- A: all or nothing\n-- C: valid state\n-- I: concurrent isolation\n-- D: persisted on commit', ['Atomicity via undo logs', 'Isolation via locking/MVCC', 'Durability via write-ahead log']],
  ['dbms', 'Transaction Management', 'Isolation Levels', 'Advanced', 'Controls how transaction changes are visible to others, balancing consistency vs performance: Read Uncommitted to Serializable.', 'SET TRANSACTION ISOLATION LEVEL READ COMMITTED;', ['Read Uncommitted, Read Committed', 'Repeatable Read, Serializable', 'Higher isolation = more locks']],
  ['dbms', 'NoSQL & Distributed Databases', 'CAP Theorem', 'Advanced', 'A distributed system can only guarantee two of three properties: Consistency, Availability, and Partition Tolerance.', '// CP: HBase, AP: Cassandra, CA: single node', ['Partition tolerance is mandatory', 'Trade-off between C and A', 'Brewer theorem']],
  ['dbms', 'NoSQL & Distributed Databases', 'BASE Model', 'Intermediate', 'Basically Available, Soft state, Eventually consistent model used by NoSQL databases instead of ACID.', '// Eventual consistency over strong consistency', ['Basically Available', 'Soft state (may change over time)', 'Eventual consistency']],

  // ===== oop (7) =====
  ['oop', 'Core OOP Principles', 'Encapsulation', 'Beginner', 'Bundling data and methods within a class while restricting direct access to internal state through access modifiers.', 'class BankAccount {\n  private balance: number;\n  deposit(amount) { this.balance += amount; }\n}', ['Hides internal state', 'Public/protected/private modifiers', 'Reduces coupling']],
  ['oop', 'Core OOP Principles', 'Inheritance', 'Beginner', 'A mechanism where a child class derives properties and behavior from a parent class, promoting code reuse.', 'class Animal { eat() {} }\nclass Dog extends Animal { bark() {} }', ['IS-A relationship', 'Method overriding', 'Single vs multiple inheritance']],
  ['oop', 'Core OOP Principles', 'Polymorphism', 'Intermediate', 'The ability of objects of different types to respond to the same method call with their own implementation.', 'interface Shape { area(): number }\nclass Circle implements Shape { area() { return 3.14 * r * r; } }', ['Compile-time (overloading)', 'Runtime (overriding)', 'Implemented via interfaces or virtual methods']],
  ['oop', 'Design Patterns & Principles', 'Singleton', 'Intermediate', 'A creational pattern ensuring a class has exactly one instance and providing a global access point to it.', 'class Singleton {\n  private static instance: Singleton;\n  static getInstance() {\n    if (!this.instance) this.instance = new Singleton();\n    return this.instance;\n  }\n}', ['Private constructor', 'Global access point', 'Thread safety concern']],
  ['oop', 'Design Patterns & Principles', 'SOLID Principles', 'Intermediate', 'Five design principles for maintainable OOP: Single-responsibility, Open-closed, Liskov substitution, Interface segregation, Dependency inversion.', '// S: one class, one responsibility\n// O: open for extension, closed for modification', ['SRP: single reason to change', 'OCP: extend without modifying', 'DIP: depend on abstractions']],
  ['oop', 'UML & Object Modeling', 'Class Diagrams', 'Intermediate', 'Static structure diagrams showing classes, attributes, methods, and relationships like inheritance and associations.', '// [Person] ->> [Address]  (association)\n// [Dog] -> [Animal]  (inheritance)', ['Shows static structure', 'Relationships: association, composition', 'Multiplicity indicators']],
  ['oop', 'UML & Object Modeling', 'Sequence Diagrams', 'Intermediate', 'Interaction diagrams that show message flow between objects over time for a specific use case scenario.', '// User -> Controller: submitOrder()\n// Controller -> Order: validate()', ['Shows temporal ordering', 'Lifelines and activation bars', 'async vs sync messages']],

  // ===== os (7) =====
  ['os', 'Process & Thread Management', 'Context Switch', 'Intermediate', 'The OS saves and restores the state of a process or thread to enable multitasking on a single CPU.', '// Save PCB of current, load PCB of next', ['Kernel operation', 'Overhead includes TLB flush', 'Affected by number of processes']],
  ['os', 'Process & Thread Management', 'Scheduling Algorithms', 'Intermediate', 'Algorithms that decide which process runs next, balancing throughput, fairness, and response time.', '// FCFS, SJF, Round Robin, Priority', ['FCFS: simple but convoy effect', 'Round Robin: time quantum', 'SJF: optimal avg wait time']],
  ['os', 'Process & Thread Management', 'Deadlocks', 'Advanced', 'A state where processes wait indefinitely for resources held by each other, requiring detection or prevention.', '// Conditions: mutual exclusion, hold & wait, no preemption, circular wait', ['Four necessary conditions', 'Prevention: break one condition', 'Detection: wait-for graph']],
  ['os', 'Memory Management', 'Paging', 'Intermediate', 'A memory scheme that divides virtual memory into fixed-size pages mapped to physical frames, eliminating external fragmentation.', '// Virtual address -> page table -> physical frame', ['Eliminates external fragmentation', 'Page table per process', 'TLB caches translations']],
  ['os', 'Memory Management', 'Virtual Memory', 'Advanced', 'An abstraction that gives each process the illusion of a large, contiguous address space backed by physical RAM and disk.', '// Demand paging swaps pages between RAM and disk', ['Enables larger logical address space', 'Demand paging', 'Page faults trigger swap-in']],
  ['os', 'File Systems & I/O', 'Inodes', 'Intermediate', 'A data structure storing metadata about a file except its name, including permissions, size, and block pointers.', '// stat command shows inode metadata', ['Each file has one inode', 'Stores permissions, timestamps, block pointers', 'Directories map names to inodes']],
  ['os', 'File Systems & I/O', 'Buffered I/O', 'Intermediate', 'Data is temporarily stored in a memory buffer between the application and disk to reduce system calls.', '// stdio uses buffer; fflush() writes to disk', ['Reduces disk access count', 'User-level and kernel-level buffers', 'Flush ensures data written']],

  // ===== networks (7) =====
  ['networks', 'Network Layers & Protocols', 'TCP/IP', 'Intermediate', 'A reliable, connection-oriented transport protocol that guarantees ordered delivery with flow and congestion control.', '// Three-way handshake: SYN, SYN-ACK, ACK', ['Connection-oriented', 'Segments with sequence numbers', 'Flow control via sliding window']],
  ['networks', 'Network Layers & Protocols', 'UDP', 'Intermediate', 'A lightweight, connectionless transport protocol with minimal overhead, no delivery guarantees, and no handshake.', '// No handshake, no retransmission', ['Faster than TCP', 'No reliability guarantees', 'Used for DNS, VoIP, streaming']],
  ['networks', 'Network Layers & Protocols', 'DNS', 'Intermediate', 'Domain Name System translates human-readable domain names to IP addresses through a hierarchical resolver chain.', 'nslookup example.com', ['Hierarchical namespace', 'Recursive and iterative queries', 'Caching reduces latency']],
  ['networks', 'Routing & Forwarding', 'Subnetting', 'Intermediate', 'Dividing a larger IP network into smaller subnetworks by extending the subnet mask for efficient address allocation.', '192.168.1.0/24 -> 192.168.1.0/26 (4 subnets)', ['Reduces broadcast domains', 'CIDR notation', 'Subnet mask determines network portion']],
  ['networks', 'Routing & Forwarding', 'NAT', 'Intermediate', 'Network Address Translation maps private IP addresses to a public IP, enabling multiple devices to share one address.', '# Router rewrites source IP/port for outbound traffic', ['Conserves public IPv4 addresses', 'PAT for port-level translation', 'Hides internal network topology']],
  ['networks', 'Application Layer & Security', 'HTTP/HTTPS', 'Intermediate', 'HTTP is the application protocol for web communication; HTTPS adds TLS encryption for secure data transfer.', 'GET /api HTTP/1.1\nHost: example.com', ['Stateless protocol', 'Methods: GET, POST, PUT, DELETE', 'Status codes: 2xx, 3xx, 4xx, 5xx']],
  ['networks', 'Application Layer & Security', 'TLS', 'Advanced', 'Transport Layer Security encrypts communication between client and server with handshake, certificate validation, and symmetric encryption.', '# Handshake: cipher suite negotiation, cert exchange, key generation', ['Provides encryption and authentication', 'Certificate chain validation', 'Forward secrecy with ephemeral keys']],

  // ===== system-design (7) =====
  ['system-design', 'Scalability & Performance', 'Load Balancing', 'Intermediate', 'Distributing incoming traffic across multiple servers to improve availability, fault tolerance, and resource utilization.', '# Algorithms: round-robin, least connections, IP hash', ['Distributes request load', 'Health checks remove dead servers', 'Can be L4 (transport) or L7 (application)']],
  ['system-design', 'Scalability & Performance', 'Caching', 'Intermediate', 'Storing frequently accessed data in a fast, temporary storage layer to reduce latency and backend load.', '# Cache-aside: read from cache, miss -> db -> write cache', ['Reduces read latency', 'TTL for invalidation', 'Eviction policies: LRU, LFU, FIFO']],
  ['system-design', 'Scalability & Performance', 'CDN', 'Intermediate', 'A geographically distributed network of proxy servers that delivers static and dynamic content from edge locations.', '# Edge servers cache content close to users', ['Reduces latency', 'Offloads origin server', 'Static and dynamic acceleration']],
  ['system-design', 'Distributed Systems', 'Consistency Models', 'Advanced', 'Rules determining when a write becomes visible to reads across distributed nodes, from strong to eventual consistency.', '# Strong: linearizability; Eventual: converge over time', ['Linearizability vs eventual consistency', 'Quorum-based approaches', 'Conflict resolution strategies']],
  ['system-design', 'Distributed Systems', 'Data Partitioning', 'Advanced', 'Splitting a dataset across multiple nodes using horizontal partitioning (sharding) based on a partition key.', '# Range-based, hash-based, or directory-based partitioning', ['Improves write throughput', 'Choose partition key carefully', 'Rebalancing is challenging']],
  ['system-design', 'Design Problem Patterns', 'Rate Limiting', 'Intermediate', 'Controlling the rate of requests from a client or service using token bucket, leaky bucket, or sliding window algorithms.', '# Token bucket: refill at rate, consume per request', ['Prevents abuse', 'Algorithms: token bucket, sliding window', 'Per-user or global limits']],
  ['system-design', 'Design Problem Patterns', 'URL Shortener', 'Intermediate', 'A service that maps long URLs to short codes using base-62 encoding, with redirect logic and analytics tracking.', '# hash("long url", salt) -> base62 encode -> 7 char code', ['Base62 encoding for short codes', 'Redirect via 301/302', 'Handle collisions with retry']],
];

data.forEach(([course, topic, term, diff, defn, code, points]) => {
  console.log(fmt(course, topic, term, diff, defn, code, points));
});
